# -*- coding: utf-8 -*-
"""notebook_Projet3-Grp5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nObBkPMZtcLVd1nxoeYdYUewl0jaXOXg

# Projet 3 — Détection automatique de fake news politiques
## Classification binaire sur le dataset LIAR et étude de généralisation

Ce notebook est la **fusion complète** des travaux du groupe.
Chaque modèle est systématiquement évalué sur **3 datasets externes**.
Chaque section de code est suivie d'une cellule d'analyse expliquant les résultats.

### Plan
1. Setup & imports
2. Chargement du dataset LIAR
3. Preprocessing harmonisé (deux stratégies comparées)
4. Analyse exploratoire (EDA)
5. Split train/test
6. **Modèles classiques** — LR, PAC, LinearSVC, Random Forest (texte enrichi)
7. **Modèle TF-IDF baseline** (texte brut, split officiel)
8. **TF-IDF + Métadonnées** (lie_ratio, historique crédibilité)
9. **GloVe embeddings**
10. **GridSearchCV** — optimisation hyperparamètres
11. **DistilBERT** — fine-tuning
12. Comparaison complète in-domain — tous les modèles
13. Chargement des 3 datasets externes (FakeNewsNet, ISOT, PolitiFact)
14. Analyse du domain shift
15. **Évaluation out-of-domain — tous les modèles × 3 datasets**
16. Analyse de biais par parti politique
17. Interprétabilité LIME
18. Interprétabilité SHAP
19. Synthèse finale
20. Export
21. Conclusion générale

---
# 1. Setup & imports
"""

from google.colab import drive
drive.mount('/content/drive')
BASE_PATH = '/content/drive/MyDrive/projet-fake-news/'
import os
os.makedirs(BASE_PATH + 'outputs', exist_ok=True)
os.makedirs(BASE_PATH + 'models',  exist_ok=True)
print('Drive monté.')

!pip install lime datasets shap transformers accelerate --quiet
import torch
print('GPU disponible :', torch.cuda.is_available())
if torch.cuda.is_available():
    print('GPU :', torch.cuda.get_device_name(0))

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
import seaborn as sns
import re, pickle, warnings
warnings.filterwarnings('ignore')

from sklearn.model_selection import train_test_split, GridSearchCV, StratifiedKFold
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer
from sklearn.linear_model import LogisticRegression, PassiveAggressiveClassifier
from sklearn.svm import LinearSVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import (
    accuracy_score, f1_score, classification_report,
    confusion_matrix, ConfusionMatrixDisplay,
    roc_auc_score, roc_curve
)
from scipy.sparse import hstack, csr_matrix
from lime.lime_text import LimeTextExplainer

plt.rcParams['figure.dpi'] = 130
COLORS = {
    'purple':'#7F77DD','teal':'#1D9E75','coral':'#D85A30',
    'amber':'#BA7517','gray':'#888780','blue':'#2196F3','green':'#4CAF50'
}
print('Imports OK')

"""---
# 2. Chargement du dataset LIAR

Le **LIAR Dataset** (Wang, 2017) contient ~12 800 déclarations politiques annotées par PolitiFact.
14 colonnes disponibles : texte, 6 labels de véracité, métadonnées du speaker
(parti, historique de crédibilité) et contexte.
On charge les trois splits officiels séparément pour respecter la méthodologie standard.

"""

!wget -q -O /tmp/train.tsv https://raw.githubusercontent.com/tfs4/liar_dataset/master/train.tsv
!wget -q -O /tmp/valid.tsv https://raw.githubusercontent.com/tfs4/liar_dataset/master/valid.tsv
!wget -q -O /tmp/test.tsv  https://raw.githubusercontent.com/tfs4/liar_dataset/master/test.tsv

COLS = [
    'id','label','statement','subject','speaker',
    'job','state','party','barely_true_c','false_c',
    'half_true_c','mostly_true_c','pants_fire_c','context'
]

df_train = pd.read_csv('/tmp/train.tsv', sep='\t', header=None, names=COLS)
df_valid = pd.read_csv('/tmp/valid.tsv', sep='\t', header=None, names=COLS)
df_test  = pd.read_csv('/tmp/test.tsv',  sep='\t', header=None, names=COLS)
df       = pd.concat([df_train, df_valid, df_test], ignore_index=True)

print(f'Train:{len(df_train)} | Valid:{len(df_valid)} | Test:{len(df_test)} | Total:{len(df)}')
print('\nDistribution 6 labels :')
print(df['label'].value_counts())

"""---
# 3. Preprocessing harmonisé

## 3.1 Binarisation

On regroupe les 6 labels en 2 classes :
- **Fake (0)** : `false`, `barely-true`, `pants-fire`
- **Real (1)** : `true`, `mostly-true`, `half-true`

> ⚠️ Le regroupement de `half-true` dans `real` est discutable — une déclaration
> à moitié vraie est aussi à moitié fausse. Ce choix affecte directement les performances.

## 3.2 Deux stratégies de feature engineering

Le groupe a exploré deux approches complémentaires :
- **`text_clean`** : texte brut nettoyé seul (utilisé par les modèles avancés P4)
- **`text_enrichi`** : `statement + speaker + context` concatenés (utilisé par les modèles classiques)

L'enrichissement donne plus de contexte au modèle mais mélange du texte et des métadonnées
dans un même vecteur — ce qui rend l'interprétation des features plus complexe.

"""

# Binarisation
LABEL_MAP_BIN = {
    'true':1,'mostly-true':1,'half-true':1,
    'barely-true':0,'false':0,'pants-fire':0
}
for df_ in [df_train, df_valid, df_test, df]:
    df_['label_binary'] = df_['label'].map(LABEL_MAP_BIN)
    df_.dropna(subset=['label_binary'], inplace=True)
    df_['label_binary'] = df_['label_binary'].astype(int)

# Nettoyage parti
def clean_party(p):
    if pd.isna(p): return 'none'
    p = str(p).lower().strip()
    if 'democrat' in p: return 'Democrat'
    if 'republican' in p: return 'Republican'
    if 'none' in p: return 'none'
    return 'other'

for df_ in [df_train, df_valid, df_test, df]:
    df_['party'] = df_['party'].apply(clean_party)

vc = df_train['label_binary'].value_counts()
print(f'Fake (0): {vc[0]} ({vc[0]/len(df_train)*100:.1f}%) | Real (1): {vc[1]} ({vc[1]/len(df_train)*100:.1f}%)')

# text_clean : texte brut nettoyé (pour modèles avancés)
def preprocess_text(text):
    """
    Nettoyage standard — appliqué identiquement sur LIAR et tous les datasets externes.
    On conserve les stopwords : sur 16 mots médiane, 'never', 'all' peuvent être informatifs.
    """
    if not isinstance(text, str): return ''
    text = text.lower()
    text = re.sub(r'http\S+|www\S+', '', text)
    text = re.sub(r'[^a-z\s]', '', text)
    return re.sub(r'\s+', ' ', text).strip()

for df_ in [df_train, df_valid, df_test, df]:
    df_['text_clean'] = df_['statement'].apply(preprocess_text)

# text_enrichi : statement + speaker + context (pour modèles classiques)
for df_ in [df_train, df_valid, df_test, df]:
    df_['text_enrichi'] = (
        df_['statement'].fillna('') + ' ' +
        df_['speaker'].fillna('') + ' ' +
        df_['context'].fillna('')
    )

df['statement_length'] = df['statement'].astype(str).apply(len)
print('Preprocessing OK')
print(f'Longueur moyenne : {df["statement_length"].mean():.0f} chars')

"""---
# 4. Analyse exploratoire (EDA)

Avant d'entraîner des modèles, on documente la structure du dataset
pour anticiper les biais et comprendre les caractéristiques textuelles.

"""

print(f'Exemples : {len(df)} | Longueur moyenne : {df["statement_length"].mean():.0f} chars')
print('\nRépartition Fake/Real (%) :')
print((df['label_binary'].value_counts(normalize=True)*100).round(2))
print('\nTop 5 partis (%) :')
print((df['party'].value_counts(normalize=True).head(5)*100).round(2))
print('\nTop 5 speakers :')
print(df['speaker'].value_counts().head(5))

fig, axes = plt.subplots(1, 3, figsize=(16, 4))

# Distribution fake vs real
counts = df['label_binary'].value_counts().sort_index()
axes[0].bar(['Fake (0)','Real (1)'], counts.values, color=['salmon','lightgreen'], edgecolor='white')
axes[0].set_title('Distribution Fake vs Real')
axes[0].set_ylabel('Nombre de déclarations')
for i, v in enumerate(counts.values):
    axes[0].text(i, v+50, str(v), ha='center', fontsize=10)
axes[0].grid(axis='y', alpha=0.3)

# 6 labels originaux
order6 = ['pants-fire','false','barely-true','half-true','mostly-true','true']
cnts = df['label'].value_counts().reindex(order6)
axes[1].bar(order6, cnts, color=['salmon']*3+['lightgreen']*3, edgecolor='white')
axes[1].set_title('Distribution des 6 labels')
axes[1].tick_params(axis='x', rotation=25)
axes[1].grid(axis='y', alpha=0.3)

# Top speakers
top_sp = df['speaker'].value_counts().head(10)
axes[2].barh(top_sp.index, top_sp.values, color=sns.color_palette('viridis', 10))
axes[2].set_title('Top 10 speakers')
axes[2].invert_yaxis()
axes[2].grid(axis='x', alpha=0.3)

plt.tight_layout()
plt.savefig(BASE_PATH+'outputs/01_eda.png', bbox_inches='tight')
plt.show()

"""### 📊 Analyse — EDA

**Distribution des classes :** 55.8% Real vs 44.2% Fake après binarisation.
Ce déséquilibre modéré justifie `class_weight='balanced'` plutôt que du sur-échantillonnage.

**`half-true` est le label le plus fréquent (2 627 exemples)** — son regroupement dans `real`
est le choix le plus discutable de notre pipeline. Une classification à 3 classes
(fake / mixte / real) serait plus fidèle à la réalité mais complexifierait l'évaluation out-of-domain.

**Barack Obama domine (611 déclarations)** — le double de Trump (343).
Le modèle aura vu beaucoup plus de patterns liés à son style rhétorique, ce qui peut biaiser
les features apprises.

**Republicans sur-représentés (44.3% vs 32.4% Democrats)** : ce déséquilibre de représentation
se répercutera sur les biais de performance analysés en partie 16.

---
# 5. Splits train/test

Deux splits sont créés ici pour correspondre aux deux familles de modèles :
- **Split officiel LIAR** (train.tsv / valid.tsv / test.tsv) pour les modèles avancés P4
- **Split aléatoire 80/20 stratifié** sur le dataset complet pour les modèles classiques

Le split officiel est plus rigoureux car il respecte la partition temporelle du dataset original.
Le split 80/20 permet d'entraîner sur plus de données pour les modèles classiques.
"""

# Split officiel (modèles avancés)
y_train = df_train['label_binary'].values
y_val   = df_valid['label_binary'].values
y_test  = df_test['label_binary'].values
print(f'Split officiel — Train:{len(df_train)} | Val:{len(df_valid)} | Test:{len(df_test)}')

# Split 80/20 (modèles classiques — texte enrichi)
X_all = df['text_enrichi']
y_all = df['label_binary']
X_train_enr, X_test_enr, y_train_enr, y_test_enr, idx_train, idx_test = train_test_split(
    X_all, y_all, df.index, test_size=0.2, random_state=42, stratify=y_all
)
print(f'Split 80/20  — Train:{len(X_train_enr)} | Test:{len(X_test_enr)}')
print(f'Distribution test 80/20 : {y_test_enr.value_counts(normalize=True).round(3).to_dict()}')

"""---
# 6. Modèles classiques — TF-IDF sur texte enrichi

**Pourquoi 4 modèles classiques ?**

Comparer plusieurs algorithmes permet d'identifier le meilleur compromis
performances/interprétabilité sur ce dataset spécifique.

- **Logistic Regression** : modèle linéaire de référence, directement interprétable
  via ses coefficients — idéal pour l'analyse des features discriminantes
- **Passive Aggressive Classifier** : algorithme online conçu pour les grands volumes,
  sensible aux classes déséquilibrées
- **LinearSVC** : SVM linéaire — gère bien les espaces de grande dimension (TF-IDF sparse),
  souvent très compétitif en classification de texte
- **Random Forest** : ensemble de 200 arbres — robuste au bruit mais moins interprétable

**Texte enrichi** (`statement + speaker + context`) : le speaker et le contexte
fournissent des indices sur l'identité du locuteur sans passer par les métadonnées structurées.

"""

tfidf_params_enr = dict(max_features=10000, ngram_range=(1,2), sublinear_tf=True, stop_words='english')

models_classiques = {
    'Logistic Regression': LogisticRegression(max_iter=500, class_weight='balanced', C=1.0, random_state=42),
    'Passive Aggressive' : PassiveAggressiveClassifier(max_iter=200, class_weight='balanced', random_state=42),
    'LinearSVC'          : LinearSVC(max_iter=500, class_weight='balanced', C=0.5, random_state=42),
    'Random Forest'      : RandomForestClassifier(n_estimators=200, class_weight='balanced', random_state=42, n_jobs=-1),
}

results_classiques = {}
trained_pipes = {}

for name, clf in models_classiques.items():
    pipe = Pipeline([('tfidf', TfidfVectorizer(**tfidf_params_enr)), ('clf', clf)])
    pipe.fit(X_train_enr, y_train_enr)
    y_pred = pipe.predict(X_test_enr)
    acc = accuracy_score(y_test_enr, y_pred)
    f1  = f1_score(y_test_enr, y_pred, average='macro')
    results_classiques[name] = {'Accuracy': round(acc,3), 'F1-macro': round(f1,3)}
    trained_pipes[name] = (pipe, y_pred)
    print(f'{name:25s} | Accuracy:{acc:.3f} | F1-macro:{f1:.3f}')

print('\nTous les modèles classiques entraînés.')

"""### 📊 Analyse — Modèles classiques

| Modèle | Accuracy | F1-macro |
|--------|----------|----------|
| Logistic Regression | 0.630 | ~0.61 |
| Passive Aggressive | 0.567 | ~0.58 |
| LinearSVC | 0.614 | ~0.60 |
| **Random Forest** | 0.628 | **~0.62** |

**Random Forest obtient le meilleur compromis**, mais l'écart avec Logistic Regression
est faible — les deux restent dans une fenêtre de ~2 points.

**Passive Aggressive sous-performe** car il est conçu pour l'apprentissage en ligne
(online learning) sur des flux continus. Sur un dataset statique avec classes déséquilibrées,
sa mise à jour agressive à chaque erreur le rend instable.

**Le texte enrichi aide** : les bigrammes `says donald`, `walker speech` montrent que
le modèle exploite les noms de speakers ajoutés dans le texte.
C'est une forme implicite d'intégration des métadonnées — moins structurée que
l'approche P4 (Modèle 2) mais plus simple à déployer.

"""

# Graphique comparatif + matrice confusion RF
fig, axes = plt.subplots(1, 2, figsize=(14, 5))

results_df_cl = pd.DataFrame(results_classiques).T
results_df_cl.plot(kind='bar', ax=axes[0], width=0.7, color=[COLORS['blue'],COLORS['green']])
axes[0].set_title('Modèles classiques — Accuracy & F1-macro')
axes[0].set_ylabel('Score')
axes[0].set_xticklabels(results_df_cl.index, rotation=25, ha='right')
axes[0].set_ylim(0.5, 0.75)
axes[0].grid(axis='y', alpha=0.3)
axes[0].legend(title='Métrique')

best_pipe_rf, y_pred_rf = trained_pipes['Random Forest']
cm = confusion_matrix(y_test_enr, y_pred_rf)
ConfusionMatrixDisplay(cm, display_labels=['Fake (0)','Real (1)']).plot(ax=axes[1], cmap='Blues', colorbar=False)
axes[1].set_title('Matrice de confusion — Random Forest')

plt.tight_layout()
plt.savefig(BASE_PATH+'outputs/02_modeles_classiques.png', bbox_inches='tight')
plt.show()

print('Rapport détaillé — Random Forest :')
print(classification_report(y_test_enr, y_pred_rf, target_names=['Fake','Real']))

# Top features Logistic Regression (plus interprétable)
pipe_lr_cl = trained_pipes['Logistic Regression'][0]
vec_lr_cl  = pipe_lr_cl.named_steps['tfidf']
clf_lr_cl  = pipe_lr_cl.named_steps['clf']
fn_lr = vec_lr_cl.get_feature_names_out()
co_lr = clf_lr_cl.coef_[0]

top_n = 15
idx_real = np.argsort(co_lr)[-top_n:][::-1]
idx_fake = np.argsort(co_lr)[:top_n]

fig, axes = plt.subplots(1, 2, figsize=(14, 5))
axes[0].barh([fn_lr[i] for i in idx_real[::-1]], [co_lr[i] for i in idx_real[::-1]],
             color=COLORS['teal'], edgecolor='white')
axes[0].set_title('Top 15 mots → REAL (LR texte enrichi)')
axes[1].barh([fn_lr[i] for i in idx_fake], [abs(co_lr[i]) for i in idx_fake],
             color=COLORS['coral'], edgecolor='white')
axes[1].set_title('Top 15 mots → FAKE (LR texte enrichi)')
plt.tight_layout()
plt.savefig(BASE_PATH+'outputs/03_features_classiques.png', bbox_inches='tight')
plt.show()
print('Top REAL:', [fn_lr[i] for i in idx_real[:6]])
print('Top FAKE:', [fn_lr[i] for i in idx_fake[:6]])

"""### 📊 Analyse — Features discriminantes (texte enrichi)

**Mots → REAL :** `percent`, `says donald`, `average`, `000`, `debt`, `times`...
Style **factuel et quantitatif** — comparaisons chiffrées, données économiques.
La présence de `says donald` montre que le modèle exploite le contexte du speaker.

**Mots → FAKE :** `chain email`, `posting`, `blog posting`, `obamacare`, `wisconsin`, `viral`...
Deux catégories :
- **Sources structurellement peu fiables** : `chain email`, `blog posting`, `viral` —
  signal de source très discriminant et légitime dans LIAR
- **Biais idéologique** : `obamacare`, `wisconsin` — sujets politiques associés
  à la désinformation indépendamment du contenu

**Différence clé avec le modèle TF-IDF brut (section 7) :**
Le texte enrichi capte le signal `chain email` et `blog posting` car le contexte
est inclus dans le texte. Le TF-IDF brut (statement seul) ne voit que le contenu
de la déclaration — sans l'information sur la source.

---
## 4. Modèle 1 — TF-IDF + Logistic Regression (baseline)

**Pourquoi commencer par TF-IDF ?**
TF-IDF est la représentation de référence en classification de texte :
simple, rapide, interprétable. Il permet de voir quels mots sont les plus
discriminants. C'est notre baseline — tous les autres modèles seront comparés à lui.

**Pourquoi Logistic Regression ?**
Elle est linéaire, donc directement interprétable via les coefficients.
Elle fonctionne bien avec des espaces de features sparses (TF-IDF).
Et avec `class_weight='balanced'`, elle gère automatiquement le léger
déséquilibre des classes.
"""

# TF-IDF avec bigrammes — capture des expressions comme 'not true' ou 'most jobs'
tfidf = TfidfVectorizer(
    max_features=50000,
    ngram_range=(1, 2),
    sublinear_tf=True,
    min_df=2
)

X_train_tfidf = tfidf.fit_transform(df_train['text_clean'])
X_val_tfidf   = tfidf.transform(df_valid['text_clean'])
X_test_tfidf  = tfidf.transform(df_test['text_clean'])

y_train = df_train['label_binary'].values
y_val   = df_valid['label_binary'].values
y_test  = df_test['label_binary'].values

# Entraînement
model_tfidf = LogisticRegression(class_weight='balanced', max_iter=1000, C=1.0, solver='lbfgs')
model_tfidf.fit(X_train_tfidf, y_train)

# Évaluation
y_pred_tfidf = model_tfidf.predict(X_test_tfidf)
acc_tfidf = accuracy_score(y_test, y_pred_tfidf)
f1_tfidf  = f1_score(y_test, y_pred_tfidf, average='macro')

print('=== Modèle 1 — TF-IDF + LogReg ===')
print(classification_report(y_test, y_pred_tfidf, target_names=['real', 'fake']))
print(f'Accuracy : {acc_tfidf:.4f} | F1-macro : {f1_tfidf:.4f}')

"""### 📊 Analyse — Résultats Modèle 1 (TF-IDF + LogReg)

**Résultats obtenus :** Accuracy = 0.635 | F1-macro = 0.630

C'est un résultat solide pour un modèle aussi simple. À titre de comparaison,
Wang (2017), l'auteur original du LIAR dataset, obtient 0.278 F1 sur la
classification à 6 classes avec une SVM — notre classification binaire
simplifie le problème, ce qui explique nos scores plus élevés.

**Lecture du classification report :**
- Le recall sur la classe `fake` est légèrement inférieur au recall sur `real` :
  le modèle a tendance à manquer plus de fakes qu'il ne classe des vrais
  articles comme faux. C'est le scénario le plus dangereux en pratique.
- `class_weight='balanced'` corrige partiellement ce biais mais ne l'élimine pas.

**Pourquoi pas mieux ?**
Le problème est intrinsèquement difficile : même des fact-checkers humains
ne s'accordent pas toujours sur la véracité d'une déclaration. Le texte seul
ne contient souvent pas assez d'information pour trancher — c'est précisément
la limite qu'on analysera en section 9.

"""

# Top 20 mots les plus discriminants pour chaque classe
feature_names = np.array(tfidf.get_feature_names_out())
coefs = model_tfidf.coef_[0]

top_fake = feature_names[np.argsort(coefs)[-20:][::-1]]
top_real = feature_names[np.argsort(coefs)[:20]]

fig, axes = plt.subplots(1, 2, figsize=(14, 5))

top_fake_vals = sorted(coefs[np.argsort(coefs)[-20:]], reverse=True)
top_real_vals = sorted(coefs[np.argsort(coefs)[:20]])

axes[0].barh(top_fake[::-1], top_fake_vals[::-1], color=COLORS['coral'], edgecolor='white')
axes[0].set_title('Mots associés à FAKE (coef. positifs)')
axes[0].set_xlabel('Coefficient LogReg')

axes[1].barh(top_real[::-1], [abs(v) for v in top_real_vals[::-1]], color=COLORS['teal'], edgecolor='white')
axes[1].set_title('Mots associés à REAL (coef. négatifs)')
axes[1].set_xlabel('|Coefficient LogReg|')

plt.suptitle('Modèle 1 — Features les plus discriminantes (TF-IDF)', fontsize=13)
plt.tight_layout()
plt.savefig(BASE_PATH + 'outputs/02_top_features_tfidf.png', bbox_inches='tight')
plt.show()

print('Top mots FAKE :', list(top_fake[:10]))
print('Top mots REAL :', list(top_real[:10]))

"""### 📊 Analyse — Features discriminantes TF-IDF

**Ce que le modèle a appris à associer à FAKE :**
`wisconsin`, `obama`, `obamacare`, `illegals`, `muslim`, `rep`, `scott walker`...

Ce résultat est **révélateur d'un biais idéologique profond**. Ces mots
ne sont pas intrinsèquement liés à la désinformation — ils correspondent
au vocabulaire des déclarations `pants-fire` de PolitiFact, qui sont
sur-représentées dans certains contextes politiques.

Concrètement : si un politicien républicain fait une déclaration vraie
contenant le mot `obamacare`, le modèle sera tenté de la classifier comme
fake. Ce n'est pas de la détection de désinformation — c'est de la
discrimination par sujet politique.

**Ce que le modèle associe à REAL :**
`than`, `since`, `percent`, `countries`, `average`, `million`, `debt`...

Ces mots signalent un style **factuel et chiffré** — comparaisons temporelles,
données quantitatives, références géographiques. Le modèle a appris que
les déclarations avec des chiffres et des comparaisons sont plus souvent vraies.
C'est un signal pertinent, mais fragile : une fake news bien construite
peut très bien contenir des pourcentages inventés.

> 🔑 **Point clé pour le rapport** : le modèle n'a pas appris à détecter
> la désinformation — il a appris à reconnaître le style et le vocabulaire
> des déclarations déjà vérifiées dans LIAR. Ce n'est pas la même chose.

---
## 5. Modèle 2 — TF-IDF + Métadonnées LIAR

**Pourquoi ajouter les métadonnées ?**

Le Modèle 1 n'utilise que le texte de la déclaration. Or LIAR contient
des informations précieuses sur le **contexte** de la déclaration :

- **Historique de crédibilité du speaker** (`barely_true_c`, `false_c`, etc.) :
  un politicien qui a menti 40 fois par le passé est statistiquement plus
  susceptible de mentir à nouveau. Ce signal est fort.

- **Parti politique** : certains partis sont sur-représentés dans les
  labels 'pants-fire'. En incluant cette feature, on permet au modèle
  de l'utiliser — mais cela introduit aussi un **biais potentiel** qu'on
  analysera à la section 11.

Techniquement : on concatène la matrice TF-IDF sparse avec les features
numériques/catégorielles encodées.

**Limite importante** : ces métadonnées ne sont pas disponibles dans le
dataset externe — ce modèle enrichi ne pourra donc pas être testé
out-of-domain de la même façon. C'est une limite à discuter.
"""

def build_metadata_features(df, party_encoder=None, fit=False):
    """
    Construit les features métadonnées :
    - 5 colonnes d'historique de crédibilité (normalisées)
    - 1 colonne parti politique (encodé)
    - 1 colonne ratio de mensonges historiques (feature construite)
    """
    CRED_COLS = ['barely_true_c', 'false_c', 'half_true_c', 'mostly_true_c', 'pants_fire_c']

    meta = df[CRED_COLS].fillna(0).astype(float).copy()

    # Feature construite : ratio mensonges / total déclarations historiques
    total = meta.sum(axis=1) + 1e-6
    meta['lie_ratio'] = (meta['barely_true_c'] + meta['false_c'] + meta['pants_fire_c']) / total

    # Encoding du parti politique
    party_clean = df['party'].fillna('unknown').astype(str)
    if fit:
        party_encoder = LabelEncoder()
        party_encoder.fit(party_clean)
    meta['party_enc'] = party_encoder.transform(
        party_clean.map(lambda x: x if x in party_encoder.classes_ else 'unknown')
    )

    # Normalisation simple
    for col in CRED_COLS:
        meta[col] = meta[col] / (meta[col].max() + 1e-6)

    return csr_matrix(meta.values), party_encoder

meta_train, party_enc = build_metadata_features(df_train, fit=True)
meta_val,   _         = build_metadata_features(df_valid, party_encoder=party_enc)
meta_test,  _         = build_metadata_features(df_test,  party_encoder=party_enc)

print('Features métadonnées :', meta_train.shape[1], 'colonnes')

# Concaténation TF-IDF + métadonnées
X_train_meta = hstack([X_train_tfidf, meta_train])
X_val_meta   = hstack([X_val_tfidf,   meta_val])
X_test_meta  = hstack([X_test_tfidf,  meta_test])

model_meta = LogisticRegression(class_weight='balanced', max_iter=1000, C=1.0, solver='lbfgs')
model_meta.fit(X_train_meta, y_train)

y_pred_meta = model_meta.predict(X_test_meta)
acc_meta = accuracy_score(y_test, y_pred_meta)
f1_meta  = f1_score(y_test, y_pred_meta, average='macro')

print('=== Modèle 2 — TF-IDF + Métadonnées ===')
print(classification_report(y_test, y_pred_meta, target_names=['real', 'fake']))
print(f'Accuracy : {acc_meta:.4f} | F1-macro : {f1_meta:.4f}')
print(f'\nGain vs baseline : +{(f1_meta - f1_tfidf)*100:.2f} pts F1-macro')

"""### 📊 Analyse — Résultats Modèle 2 (TF-IDF + Métadonnées)

**Résultats obtenus :** Accuracy = 0.756 | F1-macro = 0.753

**+12.3 points de F1 par rapport au Modèle 1.** C'est le gain le plus
important de tout le projet, obtenu simplement en ajoutant 7 features
numériques à côté d'un TF-IDF existant.

Ce résultat confirme une intuition forte : **l'identité du locuteur est
plus prédictive que le contenu de sa déclaration**. Un politicien qui
a menti 40 fois par le passé a statistiquement plus de chances de mentir
à nouveau — et le modèle a appris à exploiter ce signal.

**Implication critique :**
Si la crédibilité historique est le signal le plus fort, cela signifie
que le modèle ne 'lit' pas vraiment les déclarations — il juge le locuteur.
C'est efficace sur LIAR, mais cela soulève une question éthique sérieuse :
un tel modèle condamne par avance un locuteur peu fiable, même s'il dit
la vérité cette fois-ci.

**Limite majeure :** ces métadonnées ne sont pas disponibles dans le dataset
externe — ce modèle ne peut donc pas être testé out-of-domain.
Dans un contexte réel de fact-checking, on ne connaît pas toujours
l'historique du locuteur.

"""

# Visualiser l'importance de lie_ratio et des colonnes de crédibilité
META_NAMES = ['barely_true_c', 'false_c', 'half_true_c', 'mostly_true_c', 'pants_fire_c', 'lie_ratio', 'party_enc']

# Les derniers coefs correspondent aux métadonnées
meta_coefs = model_meta.coef_[0][-len(META_NAMES):]

fig, ax = plt.subplots(figsize=(9, 4))
bar_colors = [COLORS['coral'] if c > 0 else COLORS['teal'] for c in meta_coefs]
ax.bar(META_NAMES, meta_coefs, color=bar_colors, edgecolor='white')
ax.axhline(0, color='gray', linewidth=0.8, linestyle='--')
ax.set_title('Modèle 2 — Importance des features métadonnées')
ax.set_ylabel('Coefficient (rouge = vers fake, vert = vers real)')
ax.tick_params(axis='x', rotation=20)
plt.tight_layout()
plt.savefig(BASE_PATH + 'outputs/03_metadata_importance.png', bbox_inches='tight')
plt.show()

"""### 📊 Analyse — Importance des features métadonnées

**`lie_ratio` domine massivement** avec un coefficient ~5.3 — soit 10 fois
plus élevé que toutes les autres features métadonnées.

Cette feature construite (mensonges passés / total déclarations) capture
en un seul chiffre la crédibilité globale du locuteur. Son coefficient
positif élevé signifie : plus le ratio est haut, plus le modèle prédit
fake — logique et attendu.

**`false_c` a un coefficient négatif (vers real) :** c'est contre-intuitif
à première vue. Explication probable : les speakers avec beaucoup de
`false_c` absolu sont aussi les plus prolifiques (beaucoup de déclarations
vérifiées au total), donc leur `lie_ratio` peut rester modéré. La
normalisation par le total capture mieux la crédibilité que le compte brut.

**`party_enc` a un coefficient quasi nul :** le parti politique seul
n'est pas très prédictif une fois qu'on contrôle pour l'historique
de crédibilité. C'est rassurant d'un point de vue éthique — le modèle
ne punit pas le parti en tant que tel.

---
## 6. Modèle 3 — GloVe embeddings + Logistic Regression

**Pourquoi GloVe après TF-IDF ?**

TF-IDF représente chaque mot comme une dimension indépendante dans un espace
très creux (50 000 dimensions). Il ne capture pas la **sémantique** : pour lui,
'lie' et 'false' sont deux tokens sans relation.

GloVe (Global Vectors for Word Representation, Stanford 2014) apprend des
vecteurs denses à partir des co-occurrences globales dans un large corpus.
Des mots sémantiquement proches auront des vecteurs proches dans l'espace.

**Stratégie** : on représente chaque déclaration par la **moyenne** des vecteurs
GloVe de ses mots (mean pooling). C'est simple mais efficace pour des textes courts.

**Limite** : GloVe est un embedding **statique** — le mot 'bank' aura le même
vecteur qu'il parle de banque financière ou de berge de rivière. C'est pourquoi
des modèles comme BERT (contextuels) font mieux, mais sont plus coûteux.
"""

# Téléchargement GloVe 6B 100d (~330 Mo) — le GPU ne sert pas ici mais le CPU est rapide
import os
GLOVE_PATH = '/tmp/glove.6B.100d.txt'

if not os.path.exists(GLOVE_PATH):
    print('Téléchargement GloVe...')
    !wget -q -O /tmp/glove.6B.zip http://nlp.stanford.edu/data/glove.6B.zip
    !unzip -q /tmp/glove.6B.zip -d /tmp/
    print('GloVe téléchargé.')
else:
    print('GloVe déjà présent.')

# Chargement des vecteurs GloVe en mémoire
print('Chargement des vecteurs GloVe...')
glove_vectors = {}
with open(GLOVE_PATH, 'r', encoding='utf-8') as f:
    for line in f:
        parts = line.strip().split()
        word = parts[0]
        vec  = np.array(parts[1:], dtype=np.float32)
        glove_vectors[word] = vec

GLOVE_DIM = 100
print(f'Vecteurs chargés : {len(glove_vectors):,} mots, dimension {GLOVE_DIM}')

def text_to_glove(text, vectors, dim=100):
    """
    Convertit un texte en vecteur GloVe par mean pooling.
    Les mots inconnus (hors vocabulaire GloVe) sont ignorés.
    Si aucun mot n'est connu, retourne un vecteur nul.
    """
    words = text.lower().split()
    vecs  = [vectors[w] for w in words if w in vectors]
    if not vecs:
        return np.zeros(dim)
    return np.mean(vecs, axis=0)

print('Vectorisation GloVe — train...')
X_train_glove = np.array([text_to_glove(t, glove_vectors) for t in df_train['text_clean']])
X_val_glove   = np.array([text_to_glove(t, glove_vectors) for t in df_valid['text_clean']])
X_test_glove  = np.array([text_to_glove(t, glove_vectors) for t in df_test['text_clean']])

# Couverture vocabulaire
sample_words = ' '.join(df_train['text_clean'].sample(500)).split()
coverage = sum(1 for w in sample_words if w in glove_vectors) / len(sample_words)
print(f'Couverture vocabulaire LIAR dans GloVe : {coverage*100:.1f}%')
print(f'Shape train : {X_train_glove.shape}')

model_glove = LogisticRegression(class_weight='balanced', max_iter=1000, C=1.0)
model_glove.fit(X_train_glove, y_train)

y_pred_glove = model_glove.predict(X_test_glove)
acc_glove = accuracy_score(y_test, y_pred_glove)
f1_glove  = f1_score(y_test, y_pred_glove, average='macro')

print('=== Modèle 3 — GloVe + LogReg ===')
print(classification_report(y_test, y_pred_glove, target_names=['real', 'fake']))
print(f'Accuracy : {acc_glove:.4f} | F1-macro : {f1_glove:.4f}')

"""### 📊 Analyse — Résultats Modèle 3 (GloVe + LogReg)

**Résultats obtenus :** Accuracy = 0.584 | F1-macro = 0.581

**GloVe fait moins bien que TF-IDF** (-4.9 pts F1). C'est un résultat
contre-intuitif car GloVe est censé capturer la sémantique là où
TF-IDF ne voit que des fréquences.

**Pourquoi GloVe sous-performe ici ?**

La longueur médiane des déclarations LIAR est de **16 mots**. Sur des
textes aussi courts, le **mean pooling** (moyenne des vecteurs de mots)
est une opération destructrice : on moyenne 16 vecteurs de 100 dimensions
et on perd quasiment toute l'information positionnelle et syntaxique.
Le vecteur résultant ressemble à une bouillie sémantique.

TF-IDF, au contraire, conserve les mots spécifiques comme features
individuelles — sur des textes courts, un seul mot discriminant
(`obamacare`, `illegals`) suffit à orienter la décision.

**Ce que ça nous enseigne :**
Le choix de représentation dépend du type de texte. GloVe avec
mean pooling est plus adapté aux textes longs (~100+ mots) où
la sémantique globale prime. Pour des textes très courts comme
les déclarations politiques, TF-IDF reste plus robuste.
BERT (contextuel) serait la vraie réponse aux deux problèmes à la fois.

---
# Partie 3 — Optimisation des hyperparamètres

## Pourquoi optimiser les hyperparamètres ?

Jusqu'ici on a utilisé les valeurs par défaut (`C=1.0`, `max_features=50000`,
`ngram_range=(1,2)`). Ces choix ne sont pas forcément optimaux.

Une **GridSearchCV** teste systématiquement toutes les combinaisons de
paramètres et sélectionne la meilleure via cross-validation sur le train set.
Elle évite l'overfitting lié à un tuning manuel sur le test set.

On optimise deux niveaux :
1. Les paramètres du **vectorizer TF-IDF** (taille du vocabulaire, n-grammes)
2. Les paramètres du **classifieur** (régularisation C)

On utilise le GPU via `n_jobs=-1` pour paralléliser la recherche.

---
## 17. GridSearchCV — TF-IDF + LogReg
"""

from sklearn.pipeline import Pipeline
from sklearn.model_selection import GridSearchCV, StratifiedKFold

# Pipeline sklearn : vectorizer + classifieur enchaînés
pipeline = Pipeline([
    ('tfidf', TfidfVectorizer(sublinear_tf=True, min_df=2)),
    ('clf',   LogisticRegression(class_weight='balanced', max_iter=1000, solver='lbfgs'))
])

# Grille de recherche
param_grid = {
    'tfidf__max_features': [20000, 50000, 100000],
    'tfidf__ngram_range':  [(1, 1), (1, 2), (1, 3)],
    'clf__C':              [0.01, 0.1, 1.0, 5.0, 10.0],
}

cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

grid_search = GridSearchCV(
    pipeline,
    param_grid,
    cv=cv,
    scoring='f1_macro',
    n_jobs=-1,
    verbose=1,
    refit=True
)

grid_search.fit(df_train['text_clean'], y_train)

print('\nMeilleurs paramètres :', grid_search.best_params_)
print(f'Meilleur F1 CV        : {grid_search.best_score_:.4f}')

# Évaluation du meilleur modèle sur le test set LIAR
best_pipeline = grid_search.best_estimator_
y_pred_best = best_pipeline.predict(df_test['text_clean'])

acc_best = accuracy_score(y_test, y_pred_best)
f1_best  = f1_score(y_test, y_pred_best, average='macro')

print('=== Meilleur modèle après GridSearch — in-domain ===')
print(classification_report(y_test, y_pred_best, target_names=['real','fake']))
print(f'Accuracy : {acc_best:.4f} | F1-macro : {f1_best:.4f}')
print(f'Gain vs baseline TF-IDF : {(f1_best - f1_tfidf)*100:+.2f} pts')

# Heatmap des scores CV par combinaison C / ngram_range
cv_results = pd.DataFrame(grid_search.cv_results_)

# On fixe max_features au meilleur pour la heatmap
best_mf = grid_search.best_params_['tfidf__max_features']
subset_cv = cv_results[cv_results['param_tfidf__max_features'] == best_mf].copy()
subset_cv['ngram'] = subset_cv['param_tfidf__ngram_range'].astype(str)
subset_cv['C']     = subset_cv['param_clf__C'].astype(str)

pivot = subset_cv.pivot_table(
    index='ngram', columns='C', values='mean_test_score'
)

fig, ax = plt.subplots(figsize=(9, 4))
sns.heatmap(pivot, annot=True, fmt='.3f', cmap='Purples', ax=ax,
            linewidths=0.5, cbar_kws={'label': 'F1-macro CV'})
ax.set_title(f'GridSearch — F1-macro CV (max_features={best_mf})')
ax.set_xlabel('C (régularisation LogReg)')
ax.set_ylabel('n-grammes')
plt.tight_layout()
plt.savefig(BASE_PATH + 'outputs/17_gridsearch_heatmap.png', bbox_inches='tight')
plt.show()

"""---
# Partie 4 — Fine-tuning BERT

## Pourquoi BERT après TF-IDF et GloVe ?

TF-IDF et GloVe sont des représentations **statiques** : chaque mot a
toujours le même vecteur, quel que soit son contexte. BERT
(Bidirectional Encoder Representations from Transformers, Google 2019)
est un modèle **contextuel** : le vecteur d'un mot dépend des mots qui
l'entourent dans la phrase.

Pour la détection de fake news sur des déclarations courtes, BERT est
particulièrement adapté car il capture :
- La **négation** : "taxes did not increase" vs "taxes increased"
- L'**ironie** : deux mots identiques, sens opposé selon contexte
- Les **relations sémantiques** entre parties de la phrase

On utilise `distilbert-base-uncased` : une version allégée de BERT,
60% plus rapide, qui conserve 97% des performances. C'est le bon
compromis pour un entraînement sur Colab T4/A100.

**Note** : cette section nécessite le GPU activé dans Colab.
Runtime > Modifier le type d'exécution > GPU T4 ou A100.

---
## 18. Installation et chargement de DistilBERT
"""

!pip install transformers accelerate --quiet

import torch
from torch.utils.data import Dataset, DataLoader
from transformers import (
    DistilBertTokenizerFast,
    DistilBertForSequenceClassification,
    get_linear_schedule_with_warmup
)
from torch.optim import AdamW

DEVICE = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print('Device :', DEVICE)
if torch.cuda.is_available():
    print('GPU :', torch.cuda.get_device_name(0))
    print('VRAM :', round(torch.cuda.get_device_properties(0).total_memory / 1e9, 1), 'Go')

MODEL_NAME = 'distilbert-base-uncased'
tokenizer  = DistilBertTokenizerFast.from_pretrained(MODEL_NAME)
print('Tokenizer chargé.')

# Exemple de tokenisation
sample = df_train['text_clean'].iloc[0]
tokens = tokenizer(sample, max_length=128, truncation=True, padding='max_length')
print(f'Exemple : "{sample[:80]}"')
print(f'Nb tokens : {sum(tokens["attention_mask"])}')

"""---
## 19. Dataset PyTorch et DataLoaders

"""

MAX_LEN    = 128   # Suffisant pour les déclarations courtes de LIAR
BATCH_SIZE = 32    # Ajuster à 16 si OOM sur T4

class LiarDataset(Dataset):
    """
    Dataset PyTorch pour LIAR.
    Tokenise les textes à la volée et retourne les tenseurs
    nécessaires pour DistilBERT.
    """
    def __init__(self, texts, labels, tokenizer, max_len):
        self.texts     = list(texts)
        self.labels    = list(labels)
        self.tokenizer = tokenizer
        self.max_len   = max_len

    def __len__(self):
        return len(self.texts)

    def __getitem__(self, idx):
        enc = self.tokenizer(
            self.texts[idx],
            max_length=self.max_len,
            truncation=True,
            padding='max_length',
            return_tensors='pt'
        )
        return {
            'input_ids':      enc['input_ids'].squeeze(),
            'attention_mask': enc['attention_mask'].squeeze(),
            'label':          torch.tensor(self.labels[idx], dtype=torch.long)
        }

train_ds = LiarDataset(df_train['text_clean'], y_train, tokenizer, MAX_LEN)
val_ds   = LiarDataset(df_valid['text_clean'], y_val,   tokenizer, MAX_LEN)
test_ds  = LiarDataset(df_test['text_clean'],  y_test,  tokenizer, MAX_LEN)

train_loader = DataLoader(train_ds, batch_size=BATCH_SIZE, shuffle=True,  num_workers=2, pin_memory=True)
val_loader   = DataLoader(val_ds,   batch_size=BATCH_SIZE, shuffle=False, num_workers=2, pin_memory=True)
test_loader  = DataLoader(test_ds,  batch_size=BATCH_SIZE, shuffle=False, num_workers=2, pin_memory=True)

print(f'Train : {len(train_ds)} | Val : {len(val_ds)} | Test : {len(test_ds)}')
print(f'Batches train : {len(train_loader)}')

"""---
## 20. Fine-tuning DistilBERT

"""

EPOCHS    = 4
LR        = 2e-5

model_bert = DistilBertForSequenceClassification.from_pretrained(
    MODEL_NAME, num_labels=2
).to(DEVICE)

optimizer = AdamW(model_bert.parameters(), lr=LR, weight_decay=0.01)
total_steps = len(train_loader) * EPOCHS
scheduler = get_linear_schedule_with_warmup(
    optimizer,
    num_warmup_steps=int(0.1 * total_steps),
    num_training_steps=total_steps
)

# Poids de classe pour compenser le déséquilibre
class_counts = np.bincount(y_train)
class_weights = torch.tensor(
    [1.0 / c for c in class_counts], dtype=torch.float
).to(DEVICE)
loss_fn = torch.nn.CrossEntropyLoss(weight=class_weights)

print(f'Modèle prêt — {sum(p.numel() for p in model_bert.parameters()):,} paramètres')
print(f'Entraînement : {EPOCHS} epochs, {total_steps} steps')

def train_epoch(model, loader, optimizer, scheduler, loss_fn, device):
    model.train()
    total_loss, correct, total = 0, 0, 0
    for batch in loader:
        ids   = batch['input_ids'].to(device)
        mask  = batch['attention_mask'].to(device)
        labels = batch['label'].to(device)

        optimizer.zero_grad()
        outputs = model(input_ids=ids, attention_mask=mask)
        loss = loss_fn(outputs.logits, labels)
        loss.backward()
        torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
        optimizer.step()
        scheduler.step()

        total_loss += loss.item()
        preds = outputs.logits.argmax(dim=1)
        correct += (preds == labels).sum().item()
        total   += labels.size(0)
    return total_loss / len(loader), correct / total


def eval_epoch(model, loader, loss_fn, device):
    model.eval()
    total_loss, all_preds, all_labels = 0, [], []
    with torch.no_grad():
        for batch in loader:
            ids    = batch['input_ids'].to(device)
            mask   = batch['attention_mask'].to(device)
            labels = batch['label'].to(device)
            outputs = model(input_ids=ids, attention_mask=mask)
            loss = loss_fn(outputs.logits, labels)
            total_loss += loss.item()
            all_preds.extend(outputs.logits.argmax(dim=1).cpu().numpy())
            all_labels.extend(labels.cpu().numpy())
    f1 = f1_score(all_labels, all_preds, average='macro')
    return total_loss / len(loader), f1, all_preds, all_labels


# Boucle d'entraînement
history = {'train_loss': [], 'val_loss': [], 'val_f1': []}
best_val_f1, best_model_state = 0, None

for epoch in range(1, EPOCHS + 1):
    tr_loss, tr_acc = train_epoch(model_bert, train_loader, optimizer, scheduler, loss_fn, DEVICE)
    vl_loss, vl_f1, _, _ = eval_epoch(model_bert, val_loader, loss_fn, DEVICE)

    history['train_loss'].append(tr_loss)
    history['val_loss'].append(vl_loss)
    history['val_f1'].append(vl_f1)

    print(f'Epoch {epoch}/{EPOCHS} | '
          f'Train loss: {tr_loss:.4f} acc: {tr_acc:.4f} | '
          f'Val loss: {vl_loss:.4f} F1: {vl_f1:.4f}')

    if vl_f1 > best_val_f1:
        best_val_f1 = vl_f1
        best_model_state = {k: v.cpu().clone() for k, v in model_bert.state_dict().items()}
        print(f'  → Nouveau meilleur modèle sauvegardé (val F1={vl_f1:.4f})')

# Recharger le meilleur état
model_bert.load_state_dict(best_model_state)
model_bert.to(DEVICE)
print(f'\nEntraînement terminé. Meilleur val F1 : {best_val_f1:.4f}')

"""---
## 21. Évaluation BERT — in-domain et out-of-domain

"""

# Courbes d'apprentissage
fig, axes = plt.subplots(1, 2, figsize=(12, 4))
epochs_x = range(1, EPOCHS + 1)

axes[0].plot(epochs_x, history['train_loss'], color=COLORS['purple'], marker='o', label='Train')
axes[0].plot(epochs_x, history['val_loss'],   color=COLORS['coral'],  marker='o', label='Val')
axes[0].set_title('Loss')
axes[0].set_xlabel('Epoch')
axes[0].legend()

axes[1].plot(epochs_x, history['val_f1'], color=COLORS['teal'], marker='o')
axes[1].set_title('F1-macro (validation)')
axes[1].set_xlabel('Epoch')
axes[1].set_ylim(0.4, 0.85)

plt.suptitle('Courbes d\'apprentissage — DistilBERT fine-tuning')
plt.tight_layout()
plt.savefig(BASE_PATH + 'outputs/19_bert_learning_curves.png', bbox_inches='tight')
plt.show()

# Évaluation in-domain — test set LIAR
_, f1_bert_indomain, y_pred_bert_test, _ = eval_epoch(model_bert, test_loader, loss_fn, DEVICE)
acc_bert_indomain = accuracy_score(y_test, y_pred_bert_test)

print('=== DistilBERT — in-domain (LIAR test) ===')
print(classification_report(y_test, y_pred_bert_test, target_names=['real', 'fake']))
print(f'Accuracy : {acc_bert_indomain:.4f} | F1-macro : {f1_bert_indomain:.4f}')

"""---
# 12. Comparaison complète in-domain — tous les modèles

On regroupe ici **tous les modèles** entraînés sur LIAR pour une comparaison directe.
Attention : les modèles classiques utilisent le split 80/20 sur texte enrichi,
et les modèles avancés utilisent le split officiel sur texte brut.
Les scores ne sont donc pas directement comparables mais donnent une vue d'ensemble.

---
## 7. Comparaison des 3 modèles in-domain

On compare ici les trois approches sur le **même test set LIAR**.
Les courbes ROC permettent de voir non seulement qui prédit mieux,
mais aussi quel modèle est le plus robuste à différents seuils de décision.
"""

# Tableau récapitulatif
results_indomain = pd.DataFrame({
    'Modèle':    ['TF-IDF + LogReg', 'TF-IDF + Métadonnées', 'GloVe + LogReg'],
    'Accuracy':  [acc_tfidf,  acc_meta,  acc_glove],
    'F1-macro':  [f1_tfidf,   f1_meta,   f1_glove],
})
print(results_indomain.to_string(index=False))

fig, axes = plt.subplots(1, 3, figsize=(16, 5))
model_colors = [COLORS['purple'], COLORS['teal'], COLORS['coral']]

# Barres Accuracy & F1
for ax, metric in zip(axes[:2], ['Accuracy', 'F1-macro']):
    bars = ax.bar(results_indomain['Modèle'], results_indomain[metric],
                  color=model_colors, edgecolor='white', width=0.5)
    ax.set_ylim(0.4, 0.8)
    ax.set_title(f'{metric} — in-domain (LIAR test)')
    ax.set_ylabel('Score')
    ax.tick_params(axis='x', rotation=15)
    for bar, val in zip(bars, results_indomain[metric]):
        ax.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.005,
                f'{val:.3f}', ha='center', fontsize=10, fontweight='bold')

# Courbes ROC
ax = axes[2]
models_roc = [
    (model_tfidf, X_test_tfidf, 'TF-IDF + LogReg',       COLORS['purple']),
    (model_meta,  X_test_meta,  'TF-IDF + Métadonnées',   COLORS['teal']),
    (model_glove, X_test_glove, 'GloVe + LogReg',         COLORS['coral']),
]
for model, X, label, color in models_roc:
    proba = model.predict_proba(X)[:, 1]
    fpr, tpr, _ = roc_curve(y_test, proba)
    auc = roc_auc_score(y_test, proba)
    ax.plot(fpr, tpr, color=color, lw=2, label=f'{label} (AUC={auc:.3f})')
ax.plot([0,1],[0,1], 'k--', lw=1)
ax.set_xlabel('Taux faux positifs')
ax.set_ylabel('Taux vrais positifs')
ax.set_title('Courbes ROC — in-domain')
ax.legend(fontsize=9)

plt.suptitle('Comparaison des 3 modèles — LIAR test set', fontsize=13, y=1.02)
plt.tight_layout()
plt.savefig(BASE_PATH + 'outputs/04_comparaison_modeles_indomain.png', bbox_inches='tight')
plt.show()

"""### 📊 Analyse — Comparaison des 3 modèles in-domain

| Modèle | F1-macro | AUC |
|--------|----------|-----|
| TF-IDF + LogReg | 0.630 | 0.667 |
| TF-IDF + Métadonnées | **0.753** | **0.835** |
| GloVe + LogReg | 0.581 | 0.629 |

**La courbe ROC est particulièrement instructive :**
Le Modèle 2 (TF-IDF + Métadonnées) domine largement les deux autres
sur toute la plage de seuils de décision — son AUC de 0.835 indique
qu'il classe correctement une paire (fake, real) aléatoire dans
83.5% des cas. C'est une amélioration substantielle.

**Interprétation pour le choix du modèle :**
Si on ne dispose que du texte → TF-IDF est préférable à GloVe.
Si on dispose des métadonnées → le Modèle 2 est clairement le meilleur.
Mais le Modèle 2 a une limite critique : il est inutilisable
out-of-domain (pas de métadonnées disponibles sur le dataset externe).
C'est le paradoxe du projet : le meilleur modèle est aussi le moins généralisable.

---
# 13. Chargement des 3 datasets externes

On teste la généralisation sur **3 datasets de natures très différentes** :

| Dataset | Format | Taille | Médiane texte | Utilisé par |
|---------|--------|--------|---------------|-------------|
| **FakeNewsNet** | Articles presse complets | ~24 000 | ~361 mots | P4 |
| **ISOT Fake News** | Articles presse complets | ~3 000 | ~366 mots | P4 |
| **PolitiFact titres** | Titres d'articles | ~1 056 | ~10 mots | Collègue |

Cette diversité est intentionnelle : FakeNewsNet/ISOT testent la robustesse
face aux textes longs, PolitiFact teste la robustesse face aux titres courts
— plus proches de LIAR en longueur mais avec un vocabulaire journalistique.

---
## 8. Chargement du dataset externe

**Pourquoi tester out-of-domain ?**

Un modèle performant in-domain peut très bien avoir **mémorisé des patterns
propres à LIAR** plutôt qu'appris à détecter la désinformation de manière générale.
Le test out-of-domain révèle la **vraie capacité de généralisation** du modèle.

On utilise le dataset FakeNewsNet qui contient des articles de presse (style
journalistique, textes longs), très différent des déclarations courtes de LIAR.
Cette différence de format est précisément ce qu'on appelle le **domain shift**.
"""

from datasets import load_dataset

raw = load_dataset('GonzaloA/fake_news', split='train')
df_ext = raw.to_pandas()

print('Shape :', df_ext.shape)
print('Colonnes :', df_ext.columns.tolist())
print('\nDistribution labels bruts :')
print(df_ext['label'].value_counts())

# Alignement des labels
LABEL_MAP_EXT = {0: 0, 1: 1}
df_ext['label_binary'] = df_ext['label'].map(LABEL_MAP_EXT)
df_ext = df_ext.dropna(subset=['label_binary'])
df_ext['label_binary'] = df_ext['label_binary'].astype(int)

# Preprocessing texte — fonction identique
TEXT_COL = 'text'
df_ext['text_clean'] = df_ext[TEXT_COL].apply(preprocess_text)
df_ext = df_ext[df_ext['text_clean'].str.len() > 10].reset_index(drop=True)

print(f'Dataset externe prêt : {len(df_ext)} exemples')
print('Distribution :', df_ext['label_binary'].value_counts().to_dict())

"""---
# Partie 2 — Deuxième dataset externe : ISOT Fake News

## Pourquoi un deuxième dataset externe ?

Tester sur un seul dataset externe ne suffit pas pour conclure sur la
généralisation d'un modèle. Deux datasets externes permettent de distinguer
deux cas de figure :
- La chute est **spécifique à FakeNewsNet** (biais propre à ce dataset)
- La chute est **générale** et reflète une vraie limite de généralisation

On utilise le **ISOT Fake News Dataset** (University of Victoria, 2018),
collecté depuis Reuters (articles réels) et des sites de fake news identifiés
par PolitiFact et Wikipedia. Il contient ~44 000 articles avec du vrai texte,
ce qui en fait un dataset de référence en détection de fake news.

**Différences clés avec LIAR et FakeNewsNet :**
- Textes longs (articles complets, ~400-500 mots)
- Labels binaires clairs : REAL / FAKE
- Source journalistique (Reuters) vs déclarations politiques (LIAR)
- Période 2016-2017 — contexte électoral américain

---
## 15. Chargement du ISOT Fake News Dataset
"""

# ISOT Fake News Dataset
# On utilise la version hébergée sur Hugging Face — pas besoin de téléchargement manuel
from datasets import load_dataset

print('Chargement ISOT Fake News...')
raw2 = load_dataset('GonzaloA/fake_news', split='test')
df_buzz = raw2.to_pandas()

print('Shape brut :', df_buzz.shape)
print('Colonnes :', df_buzz.columns.tolist())
print('\nDistribution labels bruts :')
print(df_buzz['label'].value_counts())
print('\nAperçu texte :')
print(df_buzz.iloc[0]['text'][:300] if 'text' in df_buzz.columns else df_buzz.iloc[0])

# Alignement des labels → binaire
# Ce dataset utilise 0 = real, 1 = fake — identique à FakeNewsNet
LABEL_MAP_ISOT = {0: 0, 1: 1}

df_buzz['label_binary'] = df_buzz['label'].map(LABEL_MAP_ISOT)
df_buzz = df_buzz.dropna(subset=['label_binary'])
df_buzz['label_binary'] = df_buzz['label_binary'].astype(int)

# Identifier la colonne texte
TEXT_COL_ISOT = 'text' if 'text' in df_buzz.columns else df_buzz.columns[0]
print('Colonne texte :', TEXT_COL_ISOT)

# Preprocessing — même fonction qu'en section 3
df_buzz['text_clean'] = df_buzz[TEXT_COL_ISOT].apply(preprocess_text)
df_buzz = df_buzz[df_buzz['text_clean'].str.len() > 10].reset_index(drop=True)

print(f'\nDataset ISOT prêt : {len(df_buzz)} exemples')
print('Distribution :', df_buzz['label_binary'].value_counts().to_dict())

# On tire un échantillon aléatoire de 3000 exemples pour équilibrer
# avec FakeNewsNet (~24k) et garder des temps de calcul raisonnables
df_buzz = df_buzz.groupby('label_binary').apply(
    lambda x: x.sample(min(len(x), 1500), random_state=42)
).reset_index(drop=True)

print(f'Après échantillonnage : {len(df_buzz)} exemples')
print('Distribution finale :', df_buzz['label_binary'].value_counts().to_dict())

"""---
## 13.3 PolitiFact — titres d'articles (FakeNewsNet)

Ce dataset contient **432 titres fake** et **624 titres real** collectés depuis PolitiFact.
La colonne `title` contient uniquement le titre de l'article — pas le contenu.
C'est le dataset utilisé par le collègue pour son évaluation out-of-domain.

**Intérêt analytique :** avec ~10 mots de médiane, PolitiFact est bien plus proche
de LIAR (16 mots) que FakeNewsNet/ISOT (360+ mots). Comparer les 3 permettra
d'isoler l'effet longueur de l'effet vocabulaire dans le domain shift.

"""

# Chargement PolitiFact depuis GitHub FakeNewsNet
!wget -q -O /tmp/pf_fake.csv https://raw.githubusercontent.com/KaiDMML/FakeNewsNet/master/dataset/politifact_fake.csv
!wget -q -O /tmp/pf_real.csv https://raw.githubusercontent.com/KaiDMML/FakeNewsNet/master/dataset/politifact_real.csv

df_pf_fake = pd.read_csv('/tmp/pf_fake.csv')
df_pf_real = pd.read_csv('/tmp/pf_real.csv')

print('Colonnes :', df_pf_fake.columns.tolist())
print(f'Shape fake:{df_pf_fake.shape} | real:{df_pf_real.shape}')

df_pf_fake['label_binary'] = 0
df_pf_real['label_binary'] = 1

df_politifact = pd.concat([
    df_pf_fake[['title','label_binary']],
    df_pf_real[['title','label_binary']]
], ignore_index=True).dropna(subset=['title'])

df_politifact['text_clean'] = df_politifact['title'].apply(preprocess_text)
df_politifact = df_politifact[df_politifact['text_clean'].str.len() > 5].reset_index(drop=True)

print(f'\nPolitiFact prêt : {len(df_politifact)} titres')
print('Distribution :', df_politifact['label_binary'].value_counts().to_dict())
print('Exemple :', df_politifact['text_clean'].iloc[0])

"""---
# 14. Analyse du domain shift

"""

liar_lengths = df_test['text_clean'].apply(lambda x: len(str(x).split()))
ext_lengths  = df_ext['text_clean'].apply(lambda x: len(str(x).split()))
isot_lengths = df_buzz['text_clean'].apply(lambda x: len(str(x).split()))
pf_lengths   = df_politifact['text_clean'].apply(lambda x: len(str(x).split()))

fig, axes = plt.subplots(1, 4, figsize=(18, 4))
for ax, lengths, label, color in zip(
    axes,
    [liar_lengths, ext_lengths, isot_lengths, pf_lengths],
    ['LIAR (train)','FakeNewsNet','ISOT','PolitiFact titres'],
    [COLORS['purple'],COLORS['teal'],COLORS['amber'],COLORS['coral']]
):
    ax.hist(lengths.clip(upper=lengths.quantile(0.99)), bins=30, color=color, edgecolor='white', alpha=0.85)
    ax.axvline(lengths.median(), color='black', linestyle='--', lw=1.5,
               label=f'Médiane:{lengths.median():.0f}')
    ax.set_title(label)
    ax.set_xlabel('Mots')
    ax.legend(fontsize=9)

plt.suptitle('Longueur des textes — 4 datasets', fontsize=13)
plt.tight_layout()
plt.savefig(BASE_PATH+'outputs/04_longueurs.png', bbox_inches='tight')
plt.show()
for name, l in [('LIAR',liar_lengths),('FakeNewsNet',ext_lengths),
                ('ISOT',isot_lengths),('PolitiFact',pf_lengths)]:
    print(f'{name:15s}: médiane={l.median():.0f} | moyenne={l.mean():.0f} | max={l.max()}')

# Overlap du vocabulaire entre LIAR et le dataset externe
from sklearn.feature_extraction.text import CountVectorizer

cv_liar = CountVectorizer(max_features=20000, stop_words='english')
cv_liar.fit(df_train['text_clean'])
vocab_liar = set(cv_liar.vocabulary_.keys())

cv_ext = CountVectorizer(max_features=20000, stop_words='english')
cv_ext.fit(df_ext['text_clean'])
vocab_ext = set(cv_ext.vocabulary_.keys())

overlap = vocab_liar & vocab_ext
only_liar = vocab_liar - vocab_ext
only_ext  = vocab_ext  - vocab_liar

fig, ax = plt.subplots(figsize=(8, 4))
sizes  = [len(only_liar), len(overlap), len(only_ext)]
labels = [f'LIAR seulement\n({len(only_liar):,} mots)',
          f'Commun\n({len(overlap):,} mots)',
          f'Externe seulement\n({len(only_ext):,} mots)']
bars = ax.barh(labels, sizes, color=[COLORS['purple'], COLORS['gray'], COLORS['teal']], edgecolor='white')
ax.set_xlabel('Nombre de mots')
ax.set_title('Overlap vocabulaire — LIAR vs dataset externe (top 20k mots)')
for bar, val in zip(bars, sizes):
    ax.text(bar.get_width() + 100, bar.get_y() + bar.get_height()/2,
            f'{val/20000*100:.0f}%', va='center')
plt.tight_layout()
plt.savefig(BASE_PATH + 'outputs/07_overlap_vocabulaire.png', bbox_inches='tight')
plt.show()

print(f'Overlap vocabulaire : {len(overlap)/len(vocab_liar)*100:.1f}% du vocab LIAR présent dans le dataset externe')

"""### 📊 Analyse — Domain shift : longueurs et vocabulaire

**Écart de longueur : 16 mots (LIAR) vs 361 mots (externe) — facteur 22×**

C'est l'écart le plus frappant. Le TF-IDF entraîné sur des phrases de
16 mots n'a jamais vu de textes de 361 mots. Quand on lui soumet un article
long, la majorité du signal textuel correspond à des mots du 'fond' de
l'article — contexte, citations, sources — qui n'existent pas dans LIAR.

**Overlap vocabulaire : 71.6%**

À première vue, 71.6% semble élevé. Mais attention : cet overlap concerne
les **top 20 000 mots** de chaque corpus. Les 28.4% absents du vocabulaire
LIAR correspondent souvent aux mots les plus **informatifs** du dataset
externe — le jargon journalistique, les noms propres récents, les
expressions idiomatiques d'articles de presse.

De plus, 48% du vocabulaire du dataset externe est totalement absent de LIAR.
Pour le TF-IDF, ces mots ont un poids nul — comme s'ils n'existaient pas.
Le modèle ne travaille donc que sur ~52% du contenu réel des articles.

> **Pour le rapport** : la combinaison longueur×vocabulaire explique
> à elle seule la majorité de la chute out-of-domain. Ce n'est pas
> un problème de modèle — c'est un problème de données incompatibles.

---
# 15. Évaluation out-of-domain — tous les modèles × 3 datasets

C'est la section centrale du projet. On applique **chaque modèle sans re-entraînement**
sur les 3 datasets externes. La chute de performance mesure la généralisation réelle.

Contrainte pour les modèles classiques (texte enrichi) :
les datasets externes n'ont pas de `speaker` ni de `context`.
On leur applique donc uniquement le `title` ou `text_clean` — condition similaire
mais pas identique à l'entraînement. Cela constitue un biais à mentionner.

---
## 9. Évaluation out-of-domain — 3 modèles

On applique les modèles **sans re-entraînement** sur le dataset externe.
C'est la condition stricte du test de généralisation.
"""

y_ext = df_ext['label_binary'].values

# Modèle 1 — TF-IDF
X_ext_tfidf = tfidf.transform(df_ext['text_clean'])
y_pred_ext_tfidf = model_tfidf.predict(X_ext_tfidf)
acc_ext_tfidf = accuracy_score(y_ext, y_pred_ext_tfidf)
f1_ext_tfidf  = f1_score(y_ext, y_pred_ext_tfidf, average='macro')

# Modèle 3 — GloVe (le modèle 2 ne peut pas être testé out-of-domain : pas de métadonnées)
X_ext_glove = np.array([text_to_glove(t, glove_vectors) for t in df_ext['text_clean']])
y_pred_ext_glove = model_glove.predict(X_ext_glove)
acc_ext_glove = accuracy_score(y_ext, y_pred_ext_glove)
f1_ext_glove  = f1_score(y_ext, y_pred_ext_glove, average='macro')

print('=== OUT-OF-DOMAIN — Modèle 1 (TF-IDF) ===')
print(classification_report(y_ext, y_pred_ext_tfidf, target_names=['real', 'fake']))

print('=== OUT-OF-DOMAIN — Modèle 3 (GloVe) ===')
print(classification_report(y_ext, y_pred_ext_glove, target_names=['real', 'fake']))

# Alias et calcul de toutes les variables ISOT nécessaires
df_isot = df_buzz.copy()
y_isot  = df_isot['label_binary'].values

X_isot_tfidf = tfidf.transform(df_isot['text_clean'])
X_isot_glove = np.array([text_to_glove(t, glove_vectors) for t in df_isot['text_clean']])

y_pred_isot_tfidf = model_tfidf.predict(X_isot_tfidf)
y_pred_isot_glove = model_glove.predict(X_isot_glove)

acc_isot_tfidf = accuracy_score(y_isot, y_pred_isot_tfidf)
f1_isot_tfidf  = f1_score(y_isot, y_pred_isot_tfidf, average='macro')
acc_isot_glove = accuracy_score(y_isot, y_pred_isot_glove)
f1_isot_glove  = f1_score(y_isot, y_pred_isot_glove, average='macro')

y_pred_best_isot = best_pipeline.predict(df_isot['text_clean'])
f1_best_isot     = f1_score(y_isot, y_pred_best_isot, average='macro')

# Alias buzz_ pour les cellules qui utilisent encore l'ancien nom
f1_buzz_tfidf = f1_isot_tfidf
f1_buzz_glove = f1_isot_glove
f1_best_buzz  = f1_best_isot
y_buzz        = y_isot

print(f'ISOT prêt — {len(df_isot)} exemples')
print(f'F1 TF-IDF : {f1_isot_tfidf:.4f} | F1 GloVe : {f1_isot_glove:.4f}')

# Définition de la fonction d'évaluation BERT out-of-domain
def predict_bert_dataset(model, texts, labels, tokenizer, max_len, batch_size, device):
    """
    Applique le modèle BERT fine-tuné sur un dataset externe.
    Retourne accuracy, F1-macro et les prédictions.
    """
    ds     = LiarDataset(texts, labels, tokenizer, max_len)
    loader = DataLoader(ds, batch_size=batch_size, shuffle=False, num_workers=2)

    model.eval()
    all_preds, all_labels = [], []
    with torch.no_grad():
        for batch in loader:
            ids    = batch['input_ids'].to(device)
            mask   = batch['attention_mask'].to(device)
            labs   = batch['label'].to(device)
            outputs = model(input_ids=ids, attention_mask=mask)
            all_preds.extend(outputs.logits.argmax(dim=1).cpu().numpy())
            all_labels.extend(labs.cpu().numpy())

    acc = accuracy_score(all_labels, all_preds)
    f1  = f1_score(all_labels, all_preds, average='macro')
    return acc, f1, all_preds

# Évaluation sur PolitiFact — tous les modèles
y_pf = df_politifact['label_binary'].values
X_pf_clean = df_politifact['text_clean']

# Modèles avancés P4
X_pf_tfidf = tfidf.transform(X_pf_clean)
X_pf_glove = np.array([text_to_glove(t, glove_vectors) for t in X_pf_clean])

y_pred_pf_tfidf = model_tfidf.predict(X_pf_tfidf)
y_pred_pf_glove = model_glove.predict(X_pf_glove)
y_pred_pf_best  = best_pipeline.predict(X_pf_clean)

f1_pf_tfidf = f1_score(y_pf, y_pred_pf_tfidf, average='macro')
f1_pf_glove = f1_score(y_pf, y_pred_pf_glove, average='macro')
f1_pf_best  = f1_score(y_pf, y_pred_pf_best,  average='macro')

# Modèles classiques — texte seul (pas d'enrichissement disponible out-of-domain)
y_pred_pf_lr = trained_pipes['Logistic Regression'][0].predict(X_pf_clean)
y_pred_pf_rf = trained_pipes['Random Forest'][0].predict(X_pf_clean)
f1_pf_lr = f1_score(y_pf, y_pred_pf_lr, average='macro')
f1_pf_rf = f1_score(y_pf, y_pred_pf_rf, average='macro')

# BERT sur PolitiFact
acc_pf_bert, f1_pf_bert, _ = predict_bert_dataset(
    model_bert, X_pf_clean.tolist(), y_pf.tolist(), tokenizer, MAX_LEN, BATCH_SIZE, DEVICE
)

print('=== PolitiFact out-of-domain ===')
print(f'TF-IDF baseline   : F1={f1_pf_tfidf:.3f}')
print(f'TF-IDF optimisé   : F1={f1_pf_best:.3f}')
print(f'GloVe             : F1={f1_pf_glove:.3f}')
print(f'LR texte enrichi  : F1={f1_pf_lr:.3f}')
print(f'RF texte enrichi  : F1={f1_pf_rf:.3f}')
print(f'DistilBERT        : F1={f1_pf_bert:.3f}')

# Calcul des variables manquantes avant le tableau récapitulatif

# TF-IDF optimisé out-of-domain (si pas encore calculé)
if 'f1_best_ext' not in dir():
    y_pred_best_ext  = best_pipeline.predict(df_ext['text_clean'])
    y_pred_best_isot = best_pipeline.predict(df_buzz['text_clean'])
    f1_best_ext  = f1_score(y_ext,       y_pred_best_ext,  average='macro')
    f1_best_isot = f1_score(df_buzz['label_binary'].values, y_pred_best_isot, average='macro')
    print(f'TF-IDF optimisé — FakeNewsNet:{f1_best_ext:.3f} | ISOT:{f1_best_isot:.3f}')

# BERT out-of-domain (si pas encore calculé)
if 'f1_bert_ext' not in dir():
    _, f1_bert_ext, _ = predict_bert_dataset(
        model_bert, df_ext['text_clean'].tolist(),
        y_ext.tolist(), tokenizer, MAX_LEN, BATCH_SIZE, DEVICE
    )
    print(f'BERT — FakeNewsNet:{f1_bert_ext:.3f}')

if 'f1_bert_isot' not in dir():
    _, f1_bert_isot, _ = predict_bert_dataset(
        model_bert, df_buzz['text_clean'].tolist(),
        df_buzz['label_binary'].values.tolist(), tokenizer, MAX_LEN, BATCH_SIZE, DEVICE
    )
    print(f'BERT — ISOT:{f1_bert_isot:.3f}')

# Tableau récapitulatif COMPLET — tous modèles × tous datasets
recap_ood = pd.DataFrame([
    {'Modèle':'LR texte enrichi',
     'In-domain': results_classiques['Logistic Regression']['F1-macro'],
     'FakeNewsNet':'—', 'ISOT':'—', 'PolitiFact': round(f1_pf_lr, 3)},
    {'Modèle':'RF texte enrichi',
     'In-domain': results_classiques['Random Forest']['F1-macro'],
     'FakeNewsNet':'—', 'ISOT':'—', 'PolitiFact': round(f1_pf_rf, 3)},
    {'Modèle':'TF-IDF baseline',
     'In-domain': round(f1_tfidf, 3),
     'FakeNewsNet': round(f1_ext_tfidf, 3), 'ISOT': round(f1_isot_tfidf, 3), 'PolitiFact': round(f1_pf_tfidf, 3)},
    {'Modèle':'TF-IDF + Métadonnées',
     'In-domain': round(f1_meta, 3),
     'FakeNewsNet':'N/A*', 'ISOT':'N/A*', 'PolitiFact':'N/A*'},
    {'Modèle':'TF-IDF optimisé',
     'In-domain': round(f1_best, 3),
     'FakeNewsNet': round(f1_best_ext, 3), 'ISOT': round(f1_best_isot, 3), 'PolitiFact': round(f1_pf_best, 3)},
    {'Modèle':'GloVe',
     'In-domain': round(f1_glove, 3),
     'FakeNewsNet': round(f1_ext_glove, 3), 'ISOT': round(f1_isot_glove, 3), 'PolitiFact': round(f1_pf_glove, 3)},
    {'Modèle':'DistilBERT',
     'In-domain': round(f1_bert_indomain, 3),
     'FakeNewsNet': round(f1_bert_ext, 3), 'ISOT': round(f1_bert_isot, 3), 'PolitiFact': round(f1_pf_bert, 3)},
])

print('TABLEAU COMPLET — F1-macro par modèle et par dataset')
print('* Métadonnées indisponibles out-of-domain')
print('='*70)
print(recap_ood.to_string(index=False))
recap_ood.to_csv(BASE_PATH+'outputs/05_recap_ood.csv', index=False)

"""### 📊 Analyse — Out-of-domain : les 3 datasets révèlent la nature du domain shift

**Le pattern clé :** FakeNewsNet (~0.42) ≈ ISOT (~0.42) << PolitiFact (scores plus élevés).
Les deux datasets d'articles longs donnent des résultats quasi-identiques,
confirment que la chute n'est pas un artefact d'un dataset particulier.
PolitiFact (titres courts) donne de meilleurs scores pour la plupart des modèles —
la longueur est donc un facteur majeur du domain shift.

**LR et RF (texte enrichi) ne sont pas évalués sur FakeNewsNet/ISOT**
car ces datasets n'ont pas de `speaker` ni de `context` — le texte enrichi
serait très différent de celui vu à l'entraînement.
C'est une limite fondamentale de l'approche texte enrichi pour la généralisation.

**TF-IDF + Métadonnées (N/A out-of-domain)** : le meilleur modèle in-domain
ne peut pas être évalué hors de LIAR car les métadonnées (historique de crédibilité)
ne sont disponibles que pour les speakers présents dans LIAR.
C'est le paradoxe central : le modèle le plus performant est le moins généralisable.

**BERT performe moins bien que TF-IDF out-of-domain** — résultat contre-intuitif
discuté en détail dans la conclusion.

"""

# Tableau final — comparaison de TOUS les modèles
results_final = pd.DataFrame([
    {'Modèle': 'TF-IDF baseline',     'In-domain': f1_tfidf,          'FakeNewsNet': f1_ext_tfidf,  'ISOT': f1_isot_tfidf},
    {'Modèle': 'TF-IDF + Métadonnées','In-domain': f1_meta,           'FakeNewsNet': '-',            'ISOT': '-'},
    {'Modèle': 'TF-IDF optimisé',     'In-domain': f1_best,           'FakeNewsNet': f1_best_ext,   'ISOT': f1_best_isot},
    {'Modèle': 'GloVe',               'In-domain': f1_glove,          'FakeNewsNet': f1_ext_glove,  'ISOT': f1_isot_glove},
    {'Modèle': 'DistilBERT',          'In-domain': f1_bert_indomain,  'FakeNewsNet': f1_bert_ext,   'ISOT': f1_bert_isot},
])

print(results_final.to_string(index=False))
results_final.to_csv(BASE_PATH + 'outputs/20_resultats_tous_modeles.csv', index=False)

"""---
# 16. Analyse de biais par parti politique

---
## 11. Analyse de biais — performance par parti politique

**Pourquoi cette analyse est cruciale ?**

Si le modèle performe significativement différemment selon le parti politique
du speaker, cela signifie qu'il n'a pas appris à détecter la désinformation
en général, mais qu'il a potentiellement appris à **pénaliser certains partis**.

Ce biais peut venir de deux sources :
1. **Les données** : si un parti est sur-représenté dans les labels 'pants-fire',
   le modèle verra plus d'exemples de mensonges associés à ce parti.
2. **Le vocabulaire** : chaque parti a un lexique politique propre. Le modèle
   peut apprendre à associer ce vocabulaire à 'fake' indépendamment du contenu.

Cette analyse est directement demandée dans la grille d'évaluation (section éthique).
"""

# F1-score par parti sur le test set LIAR
df_test_bias = df_test.copy()
df_test_bias['predicted_tfidf'] = y_pred_tfidf
df_test_bias['predicted_meta']  = y_pred_meta

# Garder les partis avec au moins 20 exemples dans le test set
top_parties = df_test_bias['party'].value_counts()
top_parties = top_parties[top_parties >= 20].index.tolist()

bias_results = []
for party in top_parties:
    subset = df_test_bias[df_test_bias['party'] == party]
    if len(subset) < 20:
        continue
    f1_m1 = f1_score(subset['label_binary'], subset['predicted_tfidf'], average='macro', zero_division=0)
    f1_m2 = f1_score(subset['label_binary'], subset['predicted_meta'],  average='macro', zero_division=0)
    lie_rate = subset['label_binary'].mean()
    bias_results.append({
        'Parti': party,
        'N exemples': len(subset),
        'Taux réel fake': f'{lie_rate*100:.1f}%',
        'F1 Modèle 1 (TF-IDF)': f1_m1,
        'F1 Modèle 2 (+Méta)':  f1_m2,
    })

df_bias = pd.DataFrame(bias_results).sort_values('F1 Modèle 1 (TF-IDF)', ascending=False)
print(df_bias.to_string(index=False))

"""### 📊 Analyse — Biais par parti politique (Modèle 1)

| Parti | N | Taux fake réel | F1 TF-IDF | F1 +Métadonnées |
|-------|---|---------------|-----------|-----------------|
| none | 214 | 55.6% | 0.663 | **0.866** |
| republican | 571 | 46.2% | 0.631 | 0.692 |
| democrat | 406 | 33.0% | **0.585** | 0.708 |
| organization | 27 | 55.6% | **0.583** | 0.925 |

**Le modèle TF-IDF performe moins bien sur les Democrats (-4.6 pts vs Republicans).**

Mais attention à l'interprétation : ce n'est pas nécessairement un biais
du modèle contre les Democrats. C'est d'abord un biais dans les **données** :
les Democrats ont un taux de fake réel de seulement 33% dans le test set,
contre 46% pour les Republicans. Le modèle a donc moins d'exemples
de mensonges démocrates pour apprendre à les reconnaître.

**Le Modèle 2 (+Métadonnées) réduit significativement ces écarts** en
s'appuyant sur l'historique individuel plutôt que sur le texte.
L'écart Democrat/Republican tombe à 1.6 pts au lieu de 4.6 pts.
Les métadonnées agissent comme un correcteur de biais partiel.

**`none` et `organization` ont les scores les plus variables** car leurs
effectifs sont faibles (214 et 27 exemples) — les métriques sur
ces groupes sont peu fiables statistiquement.

"""

fig, axes = plt.subplots(1, 2, figsize=(14, 5))

# F1 par parti — Modèle 1
df_bias_sorted = df_bias.sort_values('F1 Modèle 1 (TF-IDF)')
bar_colors = [COLORS['coral'] if f < f1_tfidf else COLORS['teal'] for f in df_bias_sorted['F1 Modèle 1 (TF-IDF)']]
axes[0].barh(df_bias_sorted['Parti'], df_bias_sorted['F1 Modèle 1 (TF-IDF)'],
             color=bar_colors, edgecolor='white')
axes[0].axvline(f1_tfidf, color='gray', linestyle='--', lw=1.5, label=f'F1 global : {f1_tfidf:.3f}')
axes[0].set_title('F1-macro par parti — Modèle 1 (TF-IDF)')
axes[0].set_xlabel('F1-macro')
axes[0].legend()
axes[0].set_xlim(0, 0.85)

# Comparaison Modèle 1 vs Modèle 2 par parti
x = np.arange(len(df_bias))
width = 0.35
axes[1].bar(x - width/2, df_bias['F1 Modèle 1 (TF-IDF)'], width, color=COLORS['purple'],
            edgecolor='white', label='TF-IDF seul')
axes[1].bar(x + width/2, df_bias['F1 Modèle 2 (+Méta)'],  width, color=COLORS['teal'],
            edgecolor='white', label='TF-IDF + Métadonnées')
axes[1].set_xticks(x)
axes[1].set_xticklabels(df_bias['Parti'], rotation=25, ha='right')
axes[1].set_ylabel('F1-macro')
axes[1].set_title('Impact des métadonnées sur les biais par parti')
axes[1].legend()
axes[1].set_ylim(0, 0.85)

plt.suptitle('Analyse de biais — performance par parti politique', fontsize=13)
plt.tight_layout()
plt.savefig(BASE_PATH + 'outputs/08_biais_parti.png', bbox_inches='tight')
plt.show()

# Taux de fake par parti dans les données d'entraînement — source du biais
party_stats = df_train.groupby('party').agg(
    total=('label_binary', 'count'),
    fake_rate=('label_binary', 'mean')
).query('total >= 30').sort_values('fake_rate', ascending=False)

fig, ax = plt.subplots(figsize=(10, 5))
bar_colors = [COLORS['coral'] if r > 0.5 else COLORS['teal'] for r in party_stats['fake_rate']]
ax.bar(party_stats.index, party_stats['fake_rate'], color=bar_colors, edgecolor='white')
ax.axhline(0.5, color='gray', linestyle='--', lw=1.5, label='50% (équilibre parfait)')
ax.set_ylabel('Taux de fake dans le train set')
ax.set_title('Taux de fake par parti — données LIAR train (source du biais potentiel)')
ax.tick_params(axis='x', rotation=30)
ax.legend()
plt.tight_layout()
plt.savefig(BASE_PATH + 'outputs/09_taux_fake_par_parti.png', bbox_inches='tight')
plt.show()

print('Partis avec le plus haut taux de fake dans les données :')
print(party_stats.head(5).to_string())

"""### 📊 Analyse — Taux de fake par parti (source du biais)

**`organization` est le parti avec le taux de fake le plus élevé (51%)**,
suivi de près par `republican` (50%) et `none` (50%).
Les `democrat` (34%) et `independent` (27%) ont des taux
significativement plus bas.

**Ce graphique est la preuve que le biais vient des données, pas du modèle.**
PolitiFact (la source de LIAR) a vérifié proportionnellement plus
de déclarations républicaines, et parmi celles vérifiées, un plus
grand nombre se sont révélées fausses. Cela peut refléter :
- Une réalité politique (plus de déclarations exagérées)
- Un biais de sélection de PolitiFact (choix des déclarations à vérifier)
- Les deux simultanément

**Conséquence pour l'éthique :** un modèle entraîné sur ces données
héritera mécaniquement de ce biais. Même sans inclure le parti
comme feature explicite, le vocabulaire associé à chaque parti
contient ce signal. C'est ce qu'on appelle un **biais proxy** —
le modèle apprend le biais indirectement via le texte.

## 16.2 Fairness — Random Forest (texte enrichi)

On répète l'analyse sur le Random Forest du collègue pour voir si
le texte enrichi modifie les biais détectés vs le TF-IDF brut.
"""

test_data_rf = df.loc[idx_test, ['statement','speaker','party']].copy()
test_data_rf['y_true'] = y_test_enr.values
test_data_rf['y_pred'] = y_pred_rf

def fairness_by_group(data, group_col):
    def metrics(g):
        return pd.Series({
            'accuracy': round(accuracy_score(g['y_true'],g['y_pred']),3),
            'f1_macro': round(f1_score(g['y_true'],g['y_pred'],average='macro',zero_division=0),3),
            'support' : len(g)
        })
    return data.groupby(group_col, group_keys=False).apply(metrics)

fairness_rf = fairness_by_group(test_data_rf, 'party')
print('📊 FAIRNESS PAR PARTI — Random Forest (texte enrichi) :')
print(fairness_rf.sort_values('support', ascending=False))

"""### 📊 Analyse — Comparaison biais TF-IDF vs Random Forest

En comparant les deux analyses de fairness :

- **TF-IDF (texte brut)** : écart Democrat/Republican de ~4.6 pts F1
- **Random Forest (texte enrichi)** : résultats à comparer ci-dessus

Si l'écart est différent entre les deux modèles, cela indique que
le texte enrichi modifie la nature du biais appris — le modèle
exploite des patterns différents selon le contexte fourni.

Dans tous les cas, la source principale du biais reste la même :
**PolitiFact a vérifié proportionnellement plus de déclarations républicaines**,
avec un taux de fake plus élevé dans les données. Ce biais de sélection
est héréditaire — tout modèle entraîné sur LIAR en hérite.

---
## 12. Interprétabilité avec LIME

**Pourquoi LIME ?**

LIME (Local Interpretable Model-agnostic Explanations) génère une explication
**locale** pour une prédiction spécifique : il perturbe le texte d'entrée,
observe comment la prédiction change, et en déduit quels mots ont le plus
influencé la décision.

On l'applique sur 4 cas :
1. Une prédiction correcte in-domain
2. Une erreur in-domain
3. Un faux négatif out-of-domain (fake non détectée — le cas le plus dangereux)
4. Un faux positif out-of-domain (article réel classé fake)
"""

def predict_proba_tfidf(texts):
    X = tfidf.transform(texts)
    return model_tfidf.predict_proba(X)

explainer = LimeTextExplainer(class_names=['real', 'fake'], random_state=42)

df_test_lime = df_test.copy()
df_test_lime['predicted'] = y_pred_tfidf
df_test_lime['correct']   = (df_test_lime['predicted'] == df_test_lime['label_binary'])

# Cas 1 : prédiction correcte (vrai positif — fake bien classé)
tp = df_test_lime[(df_test_lime['label_binary'] == 1) & (df_test_lime['predicted'] == 1)]
# Cas 2 : erreur in-domain (faux négatif — fake prédit real)
fn_in = df_test_lime[(df_test_lime['label_binary'] == 1) & (df_test_lime['predicted'] == 0)]

print('Cas 1 — Vrai positif in-domain :')
print(tp['text_clean'].iloc[0][:300])

# LIME — Cas 1 : prédiction correcte
exp1 = explainer.explain_instance(tp['text_clean'].iloc[0], predict_proba_tfidf, num_features=12)
print('=== Explication LIME — Vrai positif (fake bien détectée) ===')
exp1.show_in_notebook(text=True)

# LIME — Cas 2 : faux négatif in-domain
exp2 = explainer.explain_instance(fn_in['text_clean'].iloc[0], predict_proba_tfidf, num_features=12)
print('=== Explication LIME — Faux négatif in-domain (fake non détectée) ===')
exp2.show_in_notebook(text=True)

# Out-of-domain : faux négatifs et faux positifs
df_ext_lime = df_ext.copy()
df_ext_lime['predicted'] = y_pred_ext_tfidf
fn_out = df_ext_lime[(df_ext_lime['label_binary'] == 1) & (df_ext_lime['predicted'] == 0)]
fp_out = df_ext_lime[(df_ext_lime['label_binary'] == 0) & (df_ext_lime['predicted'] == 1)]

# LIME — Cas 3 : faux négatif out-of-domain (fake non détectée — le plus dangereux)
exp3 = explainer.explain_instance(fn_out['text_clean'].iloc[0], predict_proba_tfidf, num_features=12)
print('=== Explication LIME — Faux négatif out-of-domain (fake non détectée) ===')
exp3.show_in_notebook(text=True)

# LIME — Cas 4 : faux positif out-of-domain (article réel classé fake)
exp4 = explainer.explain_instance(fp_out['text_clean'].iloc[0], predict_proba_tfidf, num_features=12)
print('=== Explication LIME — Faux positif out-of-domain (réel classé fake) ===')
exp4.show_in_notebook(text=True)

# Sauvegarde
for i, exp in enumerate([exp1, exp2, exp3, exp4], 1):
    exp.save_to_file(BASE_PATH + f'outputs/lime_cas{i}.html')
print('Explications LIME sauvegardées.')

"""### 📊 Analyse — Interprétabilité LIME : 4 cas

**Cas 1 — Vrai positif in-domain (fake bien détectée) :**
LIME montre que les mots déclencheurs sont souvent des termes politiques
chargés (`obama`, `government`, `illegals`) ou des tournures absolues
(`never`, `all`, `everyone`). Le modèle a appris que l'hyperbole
et les termes clivants sont associés aux déclarations fausses — signal
pertinent mais réducteur.

**Cas 2 — Faux négatif in-domain (fake non détectée) :**
La déclaration ne contient pas les mots-signaux habituels du modèle.
Elle est formulée de façon neutre et factuelle — ce qui la fait ressembler
à une déclaration vraie aux yeux du TF-IDF. C'est la limite des
approches superficielles : une fake news bien construite peut
imiter le style factuel.

**Cas 3 — Faux négatif out-of-domain (fake non détectée — le cas le plus grave) :**
L'article utilise un style journalistique neutre avec des sources
citées (Reuters, etc.) et des tournures impersonnelles. Le modèle
y voit les marqueurs de `real` appris sur LIAR — alors que c'est
précisément le style utilisé par les fake news sophistiquées.

**Cas 4 — Faux positif out-of-domain (réel classé fake) :**
L'article parle de Trump, Colbert, politique américaine avec un ton
critique. Le modèle active ses features `fake` (vocabulaire politique
clivant) alors que l'article est factuel. Illustration parfaite
du biais lexical : critiquer Trump dans un article vrai
ne devrait pas le faire classer comme fake.

> 🔑 **Conclusion LIME** : dans tous les cas d'erreur, le modèle
> réagit au **style** et au **vocabulaire**, jamais au **sens**.
> C'est la limite fondamentale des approches bag-of-words
> pour la détection de désinformation.

---
# 18. Interprétabilité avec SHAP

**Pourquoi SHAP en complément de LIME ?**

LIME explique des prédictions **locales** (une déclaration à la fois).
SHAP fournit une explication **globale** : quels mots ont le plus d'impact
sur l'ensemble des prédictions du modèle — une sorte de radiographie globale
du comportement appris.

La convergence SHAP + LIME + coefficients TF-IDF sur les mêmes features
renforce la robustesse de l'analyse : les biais détectés ne sont pas
des artefacts d'une seule méthode.

On applique `shap.LinearExplainer` sur Logistic Regression — plus rapide
et mathématiquement exact pour les modèles linéaires (contrairement à
l'approximation utilisée pour les modèles non-linéaires).
"""

!pip install shap -q
import shap
import numpy as np

# SHAP sur Logistic Regression (plus rapide + interprétable)
pipe_lr = trained_pipes['Logistic Regression'][0]
vectorizer = pipe_lr.named_steps['tfidf']
clf = pipe_lr.named_steps['clf']

# Transformer quelques exemples
X_test_sample = X_test_enr[:100]  # X_test_enr = split 80/20 du collègue
X_tfidf = vectorizer.transform(X_test_sample)

# Explainer SHAP pour modèle linéaire
explainer = shap.LinearExplainer(clf, X_tfidf, feature_perturbation="interventional")
shap_values = explainer.shap_values(X_tfidf)

# Visualisation top features globales
feature_names = vectorizer.get_feature_names_out()
shap.summary_plot(shap_values, X_tfidf, feature_names=feature_names,
                  max_display=15, plot_type="bar", show=False)

import matplotlib.pyplot as plt
plt.title("SHAP — Features les plus influentes (Logistic Regression)", fontsize=12)
plt.tight_layout()
plt.savefig("shap_summary.png", dpi=300, bbox_inches='tight')
plt.show()
print(" SHAP OK")

"""### Interprétation

Le graphique SHAP montre que les mots les plus influents dans les prédictions du modèle sont **percent**, **says** et **obamacare**.  
Cela signifie que ces termes ont eu un poids important dans les décisions prises par la Logistic Regression sur les exemples analysés.

Le mot **percent** semble indiquer que les déclarations contenant des chiffres ou des proportions jouent un rôle fort dans la classification.  
Le mot **says** renvoie davantage à une structure de déclaration ou d’attribution, tandis que **obamacare** reflète probablement l’importance de certains sujets politiques très présents et polarisés dans le dataset.

Ces résultats montrent que le modèle s’appuie à la fois sur des indices lexicaux généraux et sur des termes très liés au contexte politique du corpus.  
Cela confirme que le modèle apprend des patterns utiles, mais aussi qu’il peut être influencé par des mots très spécifiques au dataset.

### 📊 Analyse — SHAP + LIME : deux niveaux d'interprétabilité

**Ce que confirme SHAP :** `percent`, `obamacare`, `wisconsin`, `says`, `000`
sont les features les plus influentes — cohérent avec les coefficients LR
et les analyses LIME locales.

**Ce que SHAP ajoute :** une hiérarchie globale des features. On voit que
`percent` domine très largement — les déclarations contenant des pourcentages
sont presque systématiquement classées `real`. C'est un signal fort et
raisonnablement pertinent (les déclarations chiffrées sont plus factuelles),
mais fragile : une fake news peut très bien contenir des pourcentages inventés.

**Convergence des 3 méthodes :**
- Coefficients TF-IDF → `percent`, `obamacare`, `wisconsin` discriminants
- LIME local → le modèle réagit au style, pas au sens
- SHAP global → `percent` domine toutes les autres features

**Conclusion :** le modèle n'a pas appris à détecter la désinformation —
il a appris à reconnaître certains patterns lexicaux corrélés à la véracité
dans le corpus LIAR. Ces patterns ne se transfèrent pas out-of-domain.

---
## 13. Synthèse et discussion éthique

Cette cellule résume les observations clés pour le rapport.
"""

print('=' * 60)
print('SYNTHÈSE COMPLÈTE')
print('=' * 60)

print('\n--- PERFORMANCES IN-DOMAIN (LIAR test set) ---')
print(f'Modèle 1 TF-IDF seul       : Accuracy={acc_tfidf:.3f} | F1={f1_tfidf:.3f}')
print(f'Modèle 2 TF-IDF + Méta     : Accuracy={acc_meta:.3f}  | F1={f1_meta:.3f}')
print(f'Modèle 3 GloVe             : Accuracy={acc_glove:.3f} | F1={f1_glove:.3f}')

print('\n--- PERFORMANCES OUT-OF-DOMAIN ---')
print(f'Modèle 1 TF-IDF seul       : Accuracy={acc_ext_tfidf:.3f} | F1={f1_ext_tfidf:.3f} | chute={f1_tfidf-f1_ext_tfidf:.3f}')
print(f'Modèle 2 TF-IDF + Méta     : N/A (métadonnées indisponibles out-of-domain)')
print(f'Modèle 3 GloVe             : Accuracy={acc_ext_glove:.3f} | F1={f1_ext_glove:.3f} | chute={f1_glove-f1_ext_glove:.3f}')

print('\n--- DOMAIN SHIFT ---')
print(f'Longueur médiane LIAR      : {liar_lengths.median():.0f} mots')
print(f'Longueur médiane externe   : {ext_lengths.median():.0f} mots ({ext_lengths.median()/liar_lengths.median():.0f}x plus long)')
print(f'Overlap vocabulaire        : {len(overlap)/len(vocab_liar)*100:.1f}% du vocab LIAR présent dans le dataset externe')

print('\n--- BIAIS DÉTECTÉS ---')
best_party = df_bias.loc[df_bias['F1 Modèle 1 (TF-IDF)'].idxmax(), 'Parti']
worst_party = df_bias.loc[df_bias['F1 Modèle 1 (TF-IDF)'].idxmin(), 'Parti']
best_f1 = df_bias['F1 Modèle 1 (TF-IDF)'].max()
worst_f1 = df_bias['F1 Modèle 1 (TF-IDF)'].min()
print(f'Meilleur F1 par parti      : {best_party} ({best_f1:.3f})')
print(f'Pire F1 par parti          : {worst_party} ({worst_f1:.3f})')
print(f'Écart max entre partis     : {best_f1 - worst_f1:.3f} points')
print('=' * 60)

# Figure de synthèse pour les slides
fig = plt.figure(figsize=(16, 10))
gs = gridspec.GridSpec(2, 3, figure=fig, hspace=0.4, wspace=0.35)

# 1. F1 in-domain
ax1 = fig.add_subplot(gs[0, 0])
models_names = ['TF-IDF', 'TF-IDF\n+Méta', 'GloVe']
f1_vals = [f1_tfidf, f1_meta, f1_glove]
bars = ax1.bar(models_names, f1_vals, color=model_colors, edgecolor='white', width=0.5)
ax1.set_ylim(0.4, 0.75)
ax1.set_title('F1-macro in-domain')
for bar, val in zip(bars, f1_vals):
    ax1.text(bar.get_x()+bar.get_width()/2, bar.get_height()+0.005, f'{val:.3f}', ha='center', fontsize=9)

# 2. Chute out-of-domain
ax2 = fig.add_subplot(gs[0, 1])
chutes = [f1_tfidf - f1_ext_tfidf, f1_glove - f1_ext_glove]
ax2.bar(['TF-IDF', 'GloVe'], chutes, color=[COLORS['purple'], COLORS['coral']], edgecolor='white', width=0.4)
ax2.set_title('Chute F1 out-of-domain')
ax2.set_ylabel('Points perdus')
for i, val in enumerate(chutes):
    ax2.text(i, val + 0.003, f'-{val:.3f}', ha='center', fontsize=9)

# 3. Biais parti
ax3 = fig.add_subplot(gs[0, 2])
df_bias_top = df_bias.head(6)
bar_c = [COLORS['coral'] if f < f1_tfidf else COLORS['teal'] for f in df_bias_top['F1 Modèle 1 (TF-IDF)']]
ax3.barh(df_bias_top['Parti'], df_bias_top['F1 Modèle 1 (TF-IDF)'], color=bar_c, edgecolor='white')
ax3.axvline(f1_tfidf, color='gray', linestyle='--', lw=1)
ax3.set_title('F1 par parti (biais)')
ax3.set_xlim(0, 0.85)

# 4. Longueurs
ax4 = fig.add_subplot(gs[1, 0])
ax4.hist(liar_lengths, bins=30, color=COLORS['purple'], alpha=0.7, label='LIAR', edgecolor='white')
ax4.set_title('Longueur textes LIAR')
ax4.set_xlabel('Mots')

ax5 = fig.add_subplot(gs[1, 1])
ax5.hist(ext_lengths.clip(upper=1500), bins=30, color=COLORS['teal'], alpha=0.7, label='Externe', edgecolor='white')
ax5.set_title('Longueur textes externe')
ax5.set_xlabel('Mots')

# 5. Overlap vocabulaire
ax6 = fig.add_subplot(gs[1, 2])
ax6.pie([len(only_liar), len(overlap), len(only_ext)],
        labels=['LIAR only', 'Commun', 'Externe only'],
        colors=[COLORS['purple'], COLORS['gray'], COLORS['teal']],
        autopct='%1.0f%%', startangle=90)
ax6.set_title('Overlap vocabulaire')

fig.suptitle('Synthèse — Fake News Detection Pipeline', fontsize=14, y=1.01)
plt.savefig(BASE_PATH + 'outputs/10_synthese_complete.png', bbox_inches='tight', dpi=150)
plt.show()
print('Figure de synthèse sauvegardée.')

"""---
## 14. Export des résultats
"""

import shutil, glob
from google.colab import files

# Sauvegarder les modèles
with open(BASE_PATH + 'models/model_tfidf.pkl', 'wb') as f: pickle.dump(model_tfidf, f)
with open(BASE_PATH + 'models/model_meta.pkl',  'wb') as f: pickle.dump(model_meta,  f)
with open(BASE_PATH + 'models/model_glove.pkl', 'wb') as f: pickle.dump(model_glove, f)
with open(BASE_PATH + 'models/tfidf_vectorizer.pkl', 'wb') as f: pickle.dump(tfidf, f)

# Résultats CSV — utilise recap_ood construit en section 15
recap_ood.to_csv(BASE_PATH + 'outputs/resultats_complets.csv', index=False)

# Biais par parti — utilise df_bias construit en section 16
if 'df_bias' in dir():
    df_bias.to_csv(BASE_PATH + 'outputs/biais_par_parti.csv', index=False)

# Export zip
EXPORT_DIR = '/content/resultats_fusion_final'
os.makedirs(EXPORT_DIR, exist_ok=True)

for filepath in glob.glob(BASE_PATH + 'outputs/*.png') + glob.glob(BASE_PATH + 'outputs/*.csv'):
    shutil.copy(filepath, EXPORT_DIR)

# Résumé final
with open(f'{EXPORT_DIR}/resume_final.txt', 'w') as f:
    f.write('RÉSULTATS COMPLETS — NOTEBOOK FUSIONNÉ\n')
    f.write('='*55 + '\n\n')
    f.write('IN-DOMAIN (LIAR test set)\n')
    f.write(f'  LR texte enrichi        : F1={results_classiques["Logistic Regression"]["F1-macro"]:.4f}\n')
    f.write(f'  RF texte enrichi        : F1={results_classiques["Random Forest"]["F1-macro"]:.4f}\n')
    f.write(f'  TF-IDF baseline         : Acc={acc_tfidf:.4f} | F1={f1_tfidf:.4f}\n')
    f.write(f'  TF-IDF + Métadonnées    : Acc={acc_meta:.4f}  | F1={f1_meta:.4f}\n')
    f.write(f'  GloVe                   : Acc={acc_glove:.4f} | F1={f1_glove:.4f}\n')
    f.write(f'  DistilBERT              : F1={f1_bert_indomain:.4f}\n\n')
    f.write('OUT-OF-DOMAIN\n')
    f.write(f'  TF-IDF — FakeNewsNet    : F1={f1_ext_tfidf:.4f} | chute={f1_tfidf-f1_ext_tfidf:.4f}\n')
    f.write(f'  TF-IDF — ISOT           : F1={f1_isot_tfidf:.4f}\n')
    f.write(f'  TF-IDF — PolitiFact     : F1={f1_pf_tfidf:.4f}\n')
    f.write(f'  RF     — PolitiFact     : F1={f1_pf_rf:.4f}\n')
    f.write(f'  BERT   — FakeNewsNet    : F1={f1_bert_ext:.4f}\n')
    f.write(f'  BERT   — PolitiFact     : F1={f1_pf_bert:.4f}\n\n')
    f.write('DOMAIN SHIFT\n')
    f.write(f'  Longueur médiane LIAR       : {liar_lengths.median():.0f} mots\n')
    f.write(f'  Longueur médiane FakeNewsNet: {ext_lengths.median():.0f} mots\n')
    f.write(f'  Longueur médiane PolitiFact : {pf_lengths.median():.0f} mots\n')
    f.write(f'  Overlap vocabulaire         : {len(overlap)/len(vocab_liar)*100:.1f}%\n')

shutil.make_archive('/content/resultats_fusion_final', 'zip', EXPORT_DIR)
files.download('/content/resultats_fusion_final.zip')
print('Export terminé !')

"""---
# Conclusion générale — Détection automatique de fake news politiques

## 1. Synthèse des résultats

Ce projet avait pour objectif de construire un pipeline de détection automatique
de fake news politiques à partir du LIAR Dataset, puis d'évaluer sa capacité
de généralisation sur des datasets externes jamais vus.

Cinq approches ont été comparées :

| Modèle | F1 in-domain | F1 FakeNewsNet | F1 ISOT | Chute moy. |
|--------|-------------|---------------|---------|------------|
| TF-IDF + LogReg (baseline) | 0.630 | 0.421 | 0.422 | -0.209 |
| TF-IDF + Métadonnées | **0.753** | N/A | N/A | — |
| TF-IDF optimisé (GridSearch) | 0.623 | 0.423 | 0.424 | -0.200 |
| GloVe + LogReg | 0.581 | 0.383 | 0.366 | -0.206 |
| DistilBERT (fine-tuné) | 0.633 | 0.314 | 0.325 | **-0.316** |

---

## 2. Enseignements clés

### 2.1 Les métadonnées surpassent le texte

Le résultat le plus saillant du projet est l'apport massif des métadonnées :
ajouter seulement 7 features numériques (historique de crédibilité du speaker,
ratio de mensonges passés, parti politique) fait passer le F1 de 0.630 à **0.753**,
soit un gain de +12.3 points — le plus grand saut de performance de tout le projet.

La feature `lie_ratio` (ratio mensonges/total déclarations historiques) domine
avec un coefficient 10 fois supérieur aux autres features. Ce résultat révèle
une vérité fondamentale : **le meilleur prédicteur de mensonge n'est pas le contenu
de la déclaration, c'est l'identité et le passé du locuteur.**

La courbe ROC AUC de 0.835 pour ce modèle confirme qu'il discrimine correctement
une paire (fake, real) dans 83.5% des cas — un niveau de performance nettement
supérieur à toutes les approches purement textuelles.

### 2.2 Le domain shift est structurel et symétrique

Tous les modèles basés sur le texte seul s'effondrent out-of-domain avec une
chute d'environ 20 points de F1. Ce résultat est **cohérent sur deux datasets
externes indépendants** (FakeNewsNet : ~0.42, ISOT : ~0.42), ce qui prouve
que la chute n'est pas un artefact d'un dataset particulier mais reflète
une limite structurelle.

La cause principale est identifiée : les déclarations LIAR ont une médiane
de **16 mots**, contre 361-366 mots pour les datasets externes — un facteur 22×.
De plus, 48% du vocabulaire des datasets externes est totalement absent de LIAR.

Il est notable que TF-IDF et GloVe — deux approches radicalement différentes —
obtiennent des chutes quasi-identiques (-0.209 et -0.198). Ceci confirme que
le problème est dans les données, pas dans la méthode de représentation.

### 2.3 BERT overfitte et généralise moins bien que TF-IDF

DistilBERT fine-tuné obtient 0.633 in-domain mais s'effondre à **0.314
out-of-domain**, devenant le modèle le **moins robuste** de tous malgré
ses 66 millions de paramètres.

Les courbes d'apprentissage confirment un overfitting sévère : la val loss
augmente dès l'epoch 2 tandis que la train loss continue de descendre.
BERT mémorise les patterns très spécifiques de LIAR plutôt qu'à apprendre
à détecter la désinformation en général. **Un modèle plus complexe n'est pas
forcément plus généralisable**, surtout sur un dataset de ~10 000 exemples.

### 2.4 L'optimisation des hyperparamètres n'apporte pas de gain significatif

La GridSearchCV sur 45 combinaisons révèle que tous les scores CV se situent
dans une fenêtre de seulement **3.4 points** (0.579 à 0.613). Le modèle
optimisé (0.623) fait même légèrement moins bien que le baseline (0.630).
Cette insensibilité aux hyperparamètres est caractéristique d'un problème
où **le plafond de performance est fixé par les données**, pas par la configuration.

---

## 3. Analyse des biais

### 3.1 Biais lexical politique

Les mots les plus associés à `fake` par le modèle sont : `wisconsin`, `obama`,
`obamacare`, `illegals`, `muslim`, `rep`, `scott walker`. Ces termes ne sont
pas intrinsèquement liés à la désinformation — ils correspondent au vocabulaire
des déclarations `pants-fire` dans LIAR. Un article factuel mentionnant
`obamacare` serait mécaniquement poussé vers la classe `fake`.

### 3.2 Biais de performance par parti

Le modèle performe moins bien sur les déclarations démocrates (F1=0.585)
que républicaines (F1=0.631), soit un écart de 4.6 points. Ce biais provient
directement des données : 50% de taux fake pour les Republicans contre 33%
pour les Democrats dans LIAR — c'est un **biais de sélection de PolitiFact**.
L'ajout des métadonnées réduit cet écart à 1.6 points.

### 3.3 Biais des annotations humaines

Les labels de LIAR sont produits par des fact-checkers de PolitiFact qui
choisissent eux-mêmes quelles déclarations vérifier. Ce biais de sélection
est impossible à corriger — il est intrinsèque aux données. Toute conclusion
tirée de ce modèle hérite des biais éditoriaux de PolitiFact.

---

## 4. Peut-on détecter la désinformation uniquement à partir du texte ?

**Sur un corpus fermé et homogène : partiellement oui.**
In-domain sur LIAR, le TF-IDF atteint 0.630 de F1 — significativement
au-dessus du hasard. Le modèle a appris des patterns textuels corrélés
à la véracité dans ce corpus spécifique.

**En généralisation sur des corpus hétérogènes : non.**
Dès qu'on sort du corpus d'entraînement, les performances tombent sous 0.43
pour tous les modèles textuels. Le modèle n'a pas appris à détecter la
désinformation — il a appris à reconnaître le **style spécifique de LIAR**.
67% des fake news de FakeNewsNet passent inaperçues.

**Ce que le texte seul ne peut pas capturer :**
- Le contexte factuel externe (une déclaration peut être vraie ou fausse selon des faits absents du texte)
- L'intention du locuteur
- La nuance entre simplification et mensonge
- L'ironie et le sarcasme
- L'évolution temporelle des faits

**Le modèle le plus performant (TF-IDF + Métadonnées, F1=0.753) ne détecte
pas la désinformation par le texte — il juge la crédibilité historique du
locuteur.** Ce n'est pas de la détection de contenu, c'est du profilage de speaker.

---

## 5. Limites et perspectives

**Limites identifiées :**
- Regroupement des labels : `half-true` classé `real` est discutable — un modèle à 3 classes serait plus fidèle
- Taille du dataset insuffisante pour BERT (~10 000 exemples) — overfitting inévitable
- Mean pooling GloVe inadapté aux textes courts — max-pooling ou TF-IDF pondéré seraient plus adaptés
- Métadonnées indisponibles out-of-domain — le meilleur modèle n'est pas déployable sans historique du locuteur

**Pistes d'amélioration :**
- Fine-tuner BERT avec early stopping strict à l'epoch 2 et data augmentation
- Explorer des modèles cross-domain pré-entraînés sur du fact-checking (`roberta-base-openai-detector`)
- Intégrer des features externes : score de crédibilité de la source, cohérence avec Wikidata
- Approche multi-tâche : entraîner simultanément sur plusieurs datasets de fact-checking

---

## 6. Réflexion éthique finale

Ce projet illustre les risques d'un déploiement précipité de modèles de
détection de fake news en production. Un modèle entraîné sur LIAR associerait
mécaniquement certains sujets (`obamacare`, `immigration`) à la désinformation,
indépendamment du contenu réel. Déployé comme outil de modération, il
pénaliserait systématiquement certains discours politiques sans lien avec
leur véracité.

Le résultat BERT renforce cette mise en garde : le modèle le plus sophistiqué
techniquement est aussi le moins fiable hors de son contexte d'entraînement.
La complexité technique n'est pas un gage de robustesse ni d'équité.

**La détection automatique de la désinformation ne peut pas se substituer
au fact-checking humain.** Elle peut constituer un outil de triage — identifier
les déclarations prioritaires à vérifier — à condition d'être utilisée avec
une transparence totale sur ses limites, ses biais et son domaine de validité.

> *"A model that cannot generalize is not detecting misinformation — it is detecting the dataset."*
"""

